-- lic, aqui como coordinador del grupo 5 le dire quienes 
-- trabajaron en el proyecto y que modulo les toco a cada uno, 
-- para que usted pueda evaluarnos de manera individual y grupal

-- trabajo en el modulo de personas: TODO LOS INTEGRANTES

-- trabajo en el modulo de reservacion:
-- Jorge Alberto Maradiaga Molina 20152502011
-- Josue David Ortiz Ortiz 20231003161

-- trabajo en el modulo de inventario:
-- Cindy Michelle Osorto González 20211001885
-- Joel fernando valladares CRUZ 20211024825

-- trabajo en el modulo de ventas:
-- Juan Carlos López Avila 20181033368
-- Jaziel Jafeth Funez Andino 20201003788

-- trabajo en el modulo de reportes
-- Carlos David Padilla Velásquez 20221003965  
-- Angie Rebeca Aguirre Rivera 20191007529

-- =============================================================================
-- 1. MÓDULO DE PERSONAS (PA)
-- =============================================================================
-- TODOS LOS MIEMBROS DEL GRUPO 5
CREATE TABLE PA_PERSONAS (
   COD_PERSONA    BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DE LA PERSONA'
  ,DNI            VARCHAR(255)  NOT NULL       COMMENT 'IDENTIFICACION DE LA PERSONA'
  ,PRIMER_NOMBRE  VARCHAR(255)  NOT NULL       COMMENT 'PRIMER NOMBRE DE LA PERSONA'
  ,SEGUNDO_NOMBRE VARCHAR(255)                 COMMENT 'SEGUNDO NOMBRE DE LA PERSONA'
  ,APELLIDO       VARCHAR(255)  NOT NULL       COMMENT 'APELLIDO DE LA PERSONA'
  ,SEXO           ENUM('M','F','O','D') NOT NULL COMMENT 'SEXO DE LA PERSONA'
  ,EST_CIVIL      ENUM('S','C','V') NOT NULL   COMMENT 'ESTADO CIVIL DE LA PERSONA'
  ,EDAD           TINYINT       NOT NULL       COMMENT 'EDAD DE LA PERSONA'
  ,TIP_PERSONA    ENUM('N','J') NOT NULL       COMMENT 'NATURAL O JURIDICA'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PAPERSONAS PRIMARY KEY (COD_PERSONA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_TELEFONOS (
   COD_TELEFONO   BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL NUMERO DE TELEFONO'
  ,NUM_AREA       SMALLINT       NOT NULL       COMMENT 'NUMERO DE AREA PARA LLAMAR'
  ,NUM_TELEFONO   INT           NOT NULL       COMMENT 'NUMERO DE TELEFONO'
  ,TIP_TELEFONO   ENUM('C','O','P') NOT NULL   COMMENT 'C:CELULAR O:OFICINA P:PERSONAL'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PATELEFONOS PRIMARY KEY (COD_TELEFONO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE REL_PERSONAS_TELEFONOS (
   COD_REL_PERTEL BIGINT        AUTO_INCREMENT COMMENT 'RELACION PERSONAS Y TELEFONOS'
  ,COD_PERSONA    BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_TELEFONO   BIGINT        NOT NULL       COMMENT 'CODIGO DEL TELEFONO'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_RELPERTEL PRIMARY KEY (COD_REL_PERTEL)
  ,CONSTRAINT FK_RELPERTEL_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_RELPERTEL_TELEFONO FOREIGN KEY (COD_TELEFONO) REFERENCES PA_TELEFONOS(COD_TELEFONO) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_CORREOS (
   COD_CORREO      BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL CORREO ELECTRONICO'
  ,USUARIO_CORREO  VARCHAR(200)                 COMMENT 'USUARIO DE LA DIRECCION DE CORREO'
  ,SERVIDOR_CORREO VARCHAR(200)                 COMMENT 'SERVIDOR DE LA DIRECCION DE CORREO'
  ,TIP_CORREO      ENUM('P','O')                COMMENT 'P:PERSONAL O:OFICINA'
  ,USR_INGRESO     VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO     DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PACORREOS PRIMARY KEY (COD_CORREO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE REL_PERSONAS_CORREOS (
   COD_REL_PERCOR BIGINT        AUTO_INCREMENT COMMENT 'RELACION PERSONAS Y CORREOS'
  ,COD_PERSONA    BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_CORREO     BIGINT        NOT NULL       COMMENT 'CODIGO DEL CORREO'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_RELPERCOR PRIMARY KEY (COD_REL_PERCOR)
  ,CONSTRAINT FK_RELPERCOR_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_RELPERCOR_CORREO FOREIGN KEY (COD_CORREO) REFERENCES PA_CORREOS(COD_CORREO) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_TIPO_USUARIOS (
   COD_TIPO_USR  BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL TIPO DE USUARIO'
  ,NOM_TIPO      VARCHAR(255)  NOT NULL       COMMENT 'NOMBRE DEL TIPO DE USUARIO'
  ,DES_TIPO      VARCHAR(2000) NOT NULL       COMMENT 'DESCRIPCION DEL TIPO DE USUARIO'
  
  ,CONSTRAINT PK_PATIPOUSUARIOS PRIMARY KEY (COD_TIPO_USR)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE USUARIOS (
   COD_USUARIO     BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL USUARIO'
  ,COD_PERSONA     BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_TIPO_USR    BIGINT        NOT NULL       COMMENT 'CODIGO DEL TIPO DE USUARIO'
  ,NOMBRE          VARCHAR(255)  NOT NULL       COMMENT 'NOMBRE DE USUARIO'
  ,CLAVE           VARCHAR(2000) NOT NULL       COMMENT 'CONTRASENA DEL USUARIO'
  ,TOKEN           VARCHAR(6)    NOT NULL       COMMENT 'TOKEN DE ACCESO'
  ,IND_USR         ENUM('1','0') NOT NULL       COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
  ,IND_PRIMER_ING  ENUM('1','0') NOT NULL       COMMENT 'INDICADOR DE PRIMER INGRESO'
  ,USR_INGRESO     VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO     DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_USUARIOS PRIMARY KEY (COD_USUARIO)
  ,CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_TIPO_USR_USUARIO FOREIGN KEY (COD_TIPO_USR) REFERENCES PA_TIPO_USUARIOS(COD_TIPO_USR) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_TIPO_CLIENTES (
   COD_TIPO_CLI  BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL TIPO DE CLIENTE'
  ,NOM_TIPO_CLI  VARCHAR(255)                 COMMENT 'NOMBRE DEL TIPO DE CLIENTE'
  ,DES_TIPO_CLI  VARCHAR(255)                 COMMENT 'DESCRIPCION DEL TIPO DE CLIENTE'
  ,IND_TIPO_CLI  ENUM('1','0') NOT NULL       COMMENT 'INDICADOR DEL TIPO DE CLIENTE'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PATIPOCLIENTES PRIMARY KEY (COD_TIPO_CLI)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_CLIENTES (
   COD_CLIENTE  BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL CLIENTE'
  ,COD_PERSONA  BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_TIPO_CLI BIGINT        NOT NULL       COMMENT 'CODIGO DEL TIPO DE CLIENTE'
  ,NOM_EMPRESA  VARCHAR(255)                 COMMENT 'EMPRESA A LA QUE PERTENECE EL CLIENTE'
  ,IND_CLIENTE  ENUM('1','0') NOT NULL       COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
  ,USR_INGRESO  VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO  DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PACLIENTES PRIMARY KEY (COD_CLIENTE)
  ,CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_TIPO_CLI_CLIENTE FOREIGN KEY (COD_TIPO_CLI) REFERENCES PA_TIPO_CLIENTES(COD_TIPO_CLI) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_EMPLEADOS (
   COD_EMPLEADO     BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL EMPLEADO'
  ,COD_PERSONA      BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,CARGO            VARCHAR(100)  NOT NULL       COMMENT 'CARGO DEL EMPLEADO'
  ,FEC_CONTRATACION DATE          NOT NULL       COMMENT 'FECHA DE CONTRATACION'
  ,SALARIO          DECIMAL(10,2) NOT NULL       COMMENT 'SALARIO DEL EMPLEADO'
  ,USR_INGRESO      VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO      DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PAEMPLEADOS PRIMARY KEY (COD_EMPLEADO)
  ,CONSTRAINT FK_EMPLEADO_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_PROVEEDORES (
   COD_PROVEEDOR      BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL PROVEEDOR'
  ,COD_PERSONA        BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,EMPRESA            VARCHAR(150)  NOT NULL       COMMENT 'NOMBRE DE LA EMPRESA PROVEEDORA'
  ,CATEGORIA_SERVICIO VARCHAR(100)                 COMMENT 'CATEGORIA DEL SERVICIO QUE PROVEE'
  ,USR_INGRESO        VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO        DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PAPROVEEDORES PRIMARY KEY (COD_PROVEEDOR)
  ,CONSTRAINT FK_PROVEEDOR_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;


-- =============================================================================
-- 2. MÓDULO DE RESERVACIÓN (RE)
-- =============================================================================
-- trabajo en el modulo de reservacion:
-- Jorge Alberto Maradiaga Molina 20152502011
-- Josue David Ortiz Ortiz 20231003161

CREATE TABLE RE_ESPACIO (
   COD_ESPACIO      INT           AUTO_INCREMENT COMMENT 'Codigo unico del espacio'
  ,NOM_ESPACIO      VARCHAR(100)  NOT NULL       COMMENT 'Nombre descriptivo del espacio'
  ,CAN_CAPACIDAD    INT           NOT NULL       COMMENT 'Capacidad maxima de personas'
  ,TIP_ESPACIO      ENUM('SALON','AUDITORIO','AREA_EXTERIOR','SALA_REUNION') NOT NULL COMMENT 'Tipo de espacio configurado'
  ,IND_ESTADO       ENUM('DISPONIBLE','MANTENIMIENTO','INACTIVO') NOT NULL DEFAULT 'DISPONIBLE' COMMENT 'Estado operativo del espacio'
  ,MON_PRECIO_HORA  DECIMAL(10,2) NOT NULL       COMMENT 'Precio de alquiler por hora'
  
  ,CONSTRAINT PK_REESPACIOO PRIMARY KEY (COD_ESPACIO)
  ,CONSTRAINT CK_RE_REESPACIOO_TIPESPAC CHECK (TIP_ESPACIO IN ('SALON', 'AUDITORIO', 'AREA_EXTERIOR', 'SALA_REUNION'))
  ,CONSTRAINT CK_RE_REESPACIOO_INDESTAD CHECK (IND_ESTADO IN ('DISPONIBLE', 'MANTENIMIENTO', 'INACTIVO'))
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RE_RESERVACION (
   COD_RESERVACION  INT           AUTO_INCREMENT COMMENT 'Codigo de la reservacion'
  ,COD_ESPACIO      INT           NOT NULL       COMMENT 'Codigo del espacio reservado'
  ,COD_CLIENTE      BIGINT        NOT NULL       COMMENT 'Codigo del cliente que reserva'
  ,COD_EMPLEADO     BIGINT        NOT NULL       COMMENT 'Codigo del empleado que gestiona'
  ,FEC_INICIO       DATETIME      NOT NULL       COMMENT 'Fecha y hora de inicio de la reservacion'
  ,FEC_FIN          DATETIME      NOT NULL       COMMENT 'Fecha y hora de fin de la reservacion'
  ,IND_ESTADO       ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA') NOT NULL DEFAULT 'PENDIENTE' COMMENT 'Estado actual de la reservacion'
  ,DES_NOTAS        TEXT                         COMMENT 'Notas adicionales de la reservacion'
  ,USR_INGRESO      VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha en que se ingreso el registro'
  
  ,CONSTRAINT PK_RERESERVACI PRIMARY KEY (COD_RESERVACION)
  ,CONSTRAINT FK_RERESERVACI_REESPACIO FOREIGN KEY (COD_ESPACIO) REFERENCES RE_ESPACIO(COD_ESPACIO)
  ,CONSTRAINT FK_RERESERVACI_PACLIENTES FOREIGN KEY (COD_CLIENTE) REFERENCES PA_CLIENTES(COD_CLIENTE) ON DELETE CASCADE
  ,CONSTRAINT FK_RERESERVACI_PAEMPLEADOS FOREIGN KEY (COD_EMPLEADO) REFERENCES PA_EMPLEADOS(COD_EMPLEADO) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RE_ESPACIO_OCUPADO (
   COD_ESPA_OCUP    INT           AUTO_INCREMENT COMMENT 'Codigo del bloqueo de espacio'
  ,COD_ESPACIO      INT           NOT NULL       COMMENT 'Codigo del espacio bloqueado'
  ,FEC_INICIO       DATETIME      NOT NULL       COMMENT 'Fecha de inicio del bloqueo'
  ,FEC_FIN          DATETIME      NOT NULL       COMMENT 'Fecha de fin del bloqueo'
  ,DES_MOTIVO       VARCHAR(200)                 COMMENT 'Descripcion del motivo del bloqueo'
  ,USR_INGRESO      VARCHAR(255)  NOT NULL       COMMENT 'Usuario que ingreso el registro'
  ,FEC_INGRESO      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha en que se ingreso el registro'
  
  ,CONSTRAINT PK_REESPACOCUP PRIMARY KEY (COD_ESPA_OCUP)
  ,CONSTRAINT FK_REESPACOCUP_REESPACIO FOREIGN KEY (COD_ESPACIO) REFERENCES RE_ESPACIO(COD_ESPACIO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RE_HISTORIAL_RESERVACION (
   CSC_HISTORIAL    INT           AUTO_INCREMENT COMMENT 'Consecutivo del historial'
  ,COD_RESERVACION  INT           NOT NULL       COMMENT 'Codigo de la reservacion asociada'
  ,IND_ESTADO_ANT    ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA') NOT NULL COMMENT 'Estado previo del registro'
  ,IND_ESTADO_NUE    ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA') NOT NULL COMMENT 'Estado nuevo asignado'
  ,COD_PERSONA_CAM  BIGINT        NOT NULL       COMMENT 'Codigo del usuario que cambio el estado'
  ,FEC_ADICION      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora del cambio de estado'
  
  ,CONSTRAINT PK_REHISTRESER PRIMARY KEY (CSC_HISTORIAL)
  ,CONSTRAINT FK_REHISTRESER_RERESERVACI FOREIGN KEY (COD_RESERVACION) REFERENCES RE_RESERVACION(COD_RESERVACION) ON DELETE CASCADE
  ,CONSTRAINT FK_REHISTRESER_PAPERSONAS FOREIGN KEY (COD_PERSONA_CAM) REFERENCES PA_PERSONAS(COD_PERSONA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;


-- =============================================================================
-- 3. MÓDULO DE VENTAS (VE)
-- =============================================================================

-- trabajo en el modulo de ventas:
-- Juan Carlos López Avila 20181033368
-- Jaziel Jafeth Funez Andino 20201003788

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
CREATE TABLE VE_CATEGORIA_EVENTOS (
   COD_CATEGORIA BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA CATEGORIA'
  ,NOM_CATEGORIA VARCHAR(100) NOT NULL COMMENT 'NOMBRE DE LA CATEGORIA'
  ,DES_CATEGORIA TEXT COMMENT 'DESCRIPCION DE LA CATEGORIA'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
 
  ,CONSTRAINT PK_VECATEGORIAEVENTOS PRIMARY KEY (COD_CATEGORIA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_CICLO_EVENTO (
   COD_CICLO_EVENTO INT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL CICLO'
  ,NOM_CICLO VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL CICLO (ej: ANUAL, MENSUAL, UNICO)'
  ,DES_CICLO VARCHAR(255) COMMENT 'DESCRIPCION DEL CICLO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
  ,USR_INGRESO VARCHAR(255) NOT NULL COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'

  ,CONSTRAINT PK_VECICLOEVEN PRIMARY KEY (COD_CICLO_EVENTO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_EVENTOS (
   COD_EVENTO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL EVENTO'
  ,COD_CATEGORIA BIGINT NOT NULL COMMENT 'LLAVE FORANEA DE LA CATEGORIA'
  ,COD_CICLO_EVENTO INT NOT NULL COMMENT 'LLAVE FORANEA DEL CICLO DEL EVENTO'
  ,COD_RESERVACION INT COMMENT 'LLAVE FORANEA DE LA RESERVACION DEL ESPACIO (NULLABLE)'
  ,NOM_EVENTO VARCHAR(150) NOT NULL COMMENT 'NOMBRE DEL EVENTO'
  ,DES_EVENTO TEXT COMMENT 'DESCRIPCION DEL EVENTO'
  ,FEC_EVENTO DATE NOT NULL COMMENT 'FECHA DEL EVENTO'
  ,HOR_EVENTO TIME NOT NULL COMMENT 'HORA DEL EVENTO'
  ,DES_LUGAR VARCHAR(150) NOT NULL COMMENT 'LUGAR DEL EVENTO (referencia textual de respaldo)'
  ,NUM_CAPACIDAD INT NOT NULL COMMENT 'CAPACIDAD MAXIMA DEL EVENTO'
  ,IND_ESTADO ENUM('ACTIVO','CANCELADO','FINALIZADO') NOT NULL COMMENT 'ESTADO DEL EVENTO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEEVENTOS PRIMARY KEY (COD_EVENTO)
  ,CONSTRAINT FK_VEEVENTOS_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES VE_CATEGORIA_EVENTOS(COD_CATEGORIA)
  ,CONSTRAINT FK_VEEVENTOS_CICLO FOREIGN KEY (COD_CICLO_EVENTO) REFERENCES VE_CICLO_EVENTO(COD_CICLO_EVENTO)
  ,CONSTRAINT FK_VEEVENTOS_RESERVACION FOREIGN KEY (COD_RESERVACION) REFERENCES RE_RESERVACION(COD_RESERVACION) ON DELETE SET NULL
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_BOLETOS (
   COD_BOLETO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL BOLETO'
  ,COD_EVENTO BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,TIP_BOLETO ENUM('VIP','GENERAL','PREFERENCIAL','BACKSTAGE') NOT NULL COMMENT 'TIPO DE BOLETO'
  ,MON_PRECIO DECIMAL(10,2) NOT NULL COMMENT 'PRECIO DEL BOLETO'
  ,NUM_DISPONIBLE INT NOT NULL COMMENT 'CANTIDAD DISPONIBLE'
  ,DES_BOLETO TEXT COMMENT 'DESCRIPCION DEL BOLETO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEBOLETOS PRIMARY KEY (COD_BOLETO)
  ,CONSTRAINT FK_VEBOLETOS_EVENTOS FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_VENTAS (
   COD_VENTA BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA VENTA'
  ,COD_CLIENTE BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL CLIENTE (PA_CLIENTES)'
  ,FEC_VENTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DE LA VENTA'
  ,MON_TOTAL DECIMAL(10,2) NOT NULL COMMENT 'TOTAL DE LA VENTA'
  ,IND_METODO_PAGO ENUM('EFECTIVO','TARJETA','TRANSFERENCIA') NOT NULL COMMENT 'METODO DE PAGO'
  ,IND_ESTADO_VENTA ENUM('PAGADA','PENDIENTE','CANCELADA') NOT NULL COMMENT 'ESTADO DE LA VENTA'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEVENTAS PRIMARY KEY (COD_VENTA)
  ,CONSTRAINT FK_VEVENTAS_PACLIENTES FOREIGN KEY (COD_CLIENTE) REFERENCES PA_CLIENTES(COD_CLIENTE)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_DETALLE_VENTAS (
   COD_DETALLE BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL DETALLE'
  ,COD_VENTA BIGINT NOT NULL COMMENT 'LLAVE FORANEA DE LA VENTA'
  ,COD_BOLETO BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL BOLETO'
  ,NUM_CANTIDAD INT NOT NULL COMMENT 'CANTIDAD DE BOLETOS'
  ,MON_PRECIO_UNIT DECIMAL(10,2) NOT NULL COMMENT 'PRECIO UNITARIO'
  ,MON_SUBTOTAL DECIMAL(10,2) NOT NULL COMMENT 'SUBTOTAL'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEDETALLEVENTAS PRIMARY KEY (COD_DETALLE)
  ,CONSTRAINT FK_VEDETVENT_VENTA FOREIGN KEY (COD_VENTA) REFERENCES VE_VENTAS(COD_VENTA)
  ,CONSTRAINT FK_VEDETVENT_BOLETO FOREIGN KEY (COD_BOLETO) REFERENCES VE_BOLETOS(COD_BOLETO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_PAGOS (
   COD_PAGO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL PAGO'
  ,COD_VENTA BIGINT NOT NULL COMMENT 'LLAVE FORANEA DE LA VENTA'
  ,MON_PAGO DECIMAL(10,2) NOT NULL COMMENT 'MONTO DEL PAGO'
  ,FEC_PAGO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DEL PAGO'
  ,COD_REFERENCIA VARCHAR(100) COMMENT 'REFERENCIA DEL PAGO'
  ,IND_ESTADO_PAGO ENUM('APROBADO','PENDIENTE','RECHAZADO') NOT NULL COMMENT 'ESTADO DEL PAGO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEPAGOS PRIMARY KEY (COD_PAGO)
  ,CONSTRAINT FK_VEPAGOS_VENTAS FOREIGN KEY (COD_VENTA) REFERENCES VE_VENTAS(COD_VENTA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- =============================================================================
-- 4. MÓDULO DE INVENTARIO (IN)
-- =============================================================================

-- trabajo en el modulo de inventario:
-- Cindy Michelle Osorto González 20211001885
-- Joel fernando valladares CRUZ 20211024825

CREATE TABLE IN_CATEGORIAS_INVENTARIO (
   COD_CATEGORIA BIGINT        AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA CATEGORIA'
  ,NOM_CATEGORIA VARCHAR(100)  NOT NULL COMMENT 'NOMBRE DE LA CATEGORIA'
  ,DES_CATEGORIA TEXT                   COMMENT 'DESCRIPCION DE LA CATEGORIA'
  ,DES_ICONO     VARCHAR(50)            COMMENT 'ICONO REPRESENTATIVO DE LA CATEGORIA'
  ,IND_ACTIVA    BOOLEAN       NOT NULL DEFAULT TRUE COMMENT 'INDICA SI LA CATEGORIA ESTA ACTIVA'
  ,USR_REGISTRO  VARCHAR(255)  NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO  DATETIME      NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INCATEINVE PRIMARY KEY (COD_CATEGORIA)
  ,CONSTRAINT UK_INCATEINVE_NOMCATEG UNIQUE (NOM_CATEGORIA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_ALMACENES (
   COD_ALMACEN     BIGINT        AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL ALMACEN'
  ,NOM_ALMACEN     VARCHAR(100)  NOT NULL COMMENT 'NOMBRE DEL ALMACEN'
  ,DIR_UBICACION   VARCHAR(200)           COMMENT 'UBICACION FISICA DEL ALMACEN'
  ,COD_EMPLEADO    BIGINT                 COMMENT 'LLAVE FORANEA DEL EMPLEADO RESPONSABLE DEL ALMACEN'
  ,CAN_CAPACIDAD   INT                    COMMENT 'CAPACIDAD MAXIMA DE ITEMS'
  ,IND_ACTIVO      BOOLEAN       NOT NULL DEFAULT TRUE COMMENT 'INDICA SI EL ALMACEN ESTA ACTIVO'
  ,USR_REGISTRO    VARCHAR(255)  NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO    DATETIME      NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INALMACENE PRIMARY KEY (COD_ALMACEN)
  ,CONSTRAINT FK_INALMACENE_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES PA_EMPLEADOS(COD_EMPLEADO) ON DELETE SET NULL
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_INVENTARIO_ITEM (
   COD_ITEM        BIGINT        AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL ITEM'
  ,NOM_ITEM        VARCHAR(150)  NOT NULL COMMENT 'NOMBRE DEL ITEM'
  ,DES_ITEM        TEXT                   COMMENT 'DESCRIPCION DETALLADA DEL ITEM'
  ,COD_CATEGORIA   BIGINT                 COMMENT 'LLAVE FORANEA DE CATEGORIA'
  ,COD_ALMACEN     BIGINT                 COMMENT 'LLAVE FORANEA DEL ALMACEN'
  ,CAN_TOTAL       INT           NOT NULL DEFAULT 0 COMMENT 'CANTIDAD TOTAL DEL ITEM'
  ,CAN_DISPONIBLE  INT           NOT NULL DEFAULT 0 COMMENT 'CANTIDAD DISPONIBLE DEL ITEM'
  ,IND_ESTADO      ENUM('ACTIVO','BAJA','MANTENIMIENTO') NOT NULL DEFAULT 'ACTIVO' COMMENT 'ESTADO ACTUAL DEL ITEM'
  ,COD_ITEM_UNICO  VARCHAR(50)            COMMENT 'CODIGO UNICO DEL ITEM'
  ,IMG_FOTO_URL    VARCHAR(255)           COMMENT 'URL DE LA FOTO DEL ITEM'
  ,FEC_ADQUISICION DATE                   COMMENT 'FECHA EN QUE SE ADQUIRIO EL ITEM'
  ,MON_COSTO       DECIMAL(10,2)          COMMENT 'COSTO UNITARIO DEL ITEM'
  ,USR_REGISTRO    VARCHAR(255)  NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO    DATETIME      NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_ININVEITEM PRIMARY KEY (COD_ITEM)
  ,CONSTRAINT UK_ININVEITEM_ITEMUNIQUE UNIQUE (COD_ITEM_UNICO)
  ,CONSTRAINT FK_ININVEITEM_INCATEINVE FOREIGN KEY (COD_CATEGORIA) REFERENCES IN_CATEGORIAS_INVENTARIO(COD_CATEGORIA) ON DELETE SET NULL ON UPDATE CASCADE
  ,CONSTRAINT FK_ININVEITEM_INALMACENE FOREIGN KEY (COD_ALMACEN) REFERENCES IN_ALMACENES(COD_ALMACEN) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_RESERVAS_INVENTARIO (
   COD_RESERVA          BIGINT       AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA RESERVA'
  ,COD_EVENTO          BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,COD_ITEM            BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL ITEM'
  ,CAN_RESERVADA       INT          NOT NULL COMMENT 'CANTIDAD DE ITEMS RESERVADOS'
  ,FEC_INICIO_RESERVA  DATETIME     NOT NULL COMMENT 'FECHA DE INICIO DE LA RESERVA'
  ,FEC_FIN_RESERVA     DATETIME     NOT NULL COMMENT 'FECHA DE FIN DE LA RESERVA'
  ,IND_ESTADO_RESERVA  ENUM('ACTIVA','CANCELADA','COMPLETADA') NOT NULL DEFAULT 'ACTIVA' COMMENT 'ESTADO DE LA RESERVA'
  ,NOM_SOLICITANTE     VARCHAR(100)          COMMENT 'PERSONA QUE SOLICITA LA RESERVA'
  ,DES_NOTAS           TEXT                   COMMENT 'NOTAS ADICIONALES DE LA RESERVA'
  ,USR_REGISTRO        VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO        DATETIME     NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INRESINVEN PRIMARY KEY (COD_RESERVA)
  ,CONSTRAINT FK_INRESINVEN_ININVEITEM FOREIGN KEY (COD_ITEM) REFERENCES IN_INVENTARIO_ITEM(COD_ITEM) ON DELETE RESTRICT ON UPDATE CASCADE
  ,CONSTRAINT FK_INRESINVEN_EVENTOS FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_ASIGNACION_EVENTO (
   COD_ASIGNACION    BIGINT       AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA ASIGNACION'
  ,COD_EVENTO        BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,COD_ITEM          BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL ITEM'
  ,CAN_ASIGNADA      INT          NOT NULL COMMENT 'CANTIDAD DE ITEMS ASIGNADOS AL EVENTO'
  ,FEC_SALIDA        DATETIME     NOT NULL COMMENT 'FECHA DE SALIDA DEL ITEM'
  ,FEC_RETORNO       DATETIME              COMMENT 'FECHA DE RETORNO DEL ITEM'
  ,IND_ESTADO        ENUM('PENDIENTE','ENTREGADO','RETORNADO','PERDIDO') NOT NULL DEFAULT 'PENDIENTE' COMMENT 'ESTADO DE LA ASIGNACION'
  ,IND_CONDICION     ENUM('BUENO','DANIADO','PERDIDO') COMMENT 'CONDICION DEL ITEM AL RETORNAR'
  ,NOM_RESPONSABLE   VARCHAR(100)          COMMENT 'RESPONSABLE DE LA ASIGNACION'
  ,DES_OBSERVACIONES TEXT                   COMMENT 'OBSERVACIONES DE LA ASIGNACION'
  ,USR_REGISTRO      VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO      DATETIME     NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INASIGEVEN PRIMARY KEY (COD_ASIGNACION)
  ,CONSTRAINT FK_INASIGEVEN_ININVEITEM FOREIGN KEY (COD_ITEM) REFERENCES IN_INVENTARIO_ITEM(COD_ITEM) ON DELETE RESTRICT ON UPDATE CASCADE
  ,CONSTRAINT FK_INASIGEVEN_EVENTOS FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;


-- =============================================================================
-- 5. MÓDULO DE REPORTES (RP)
-- =============================================================================

-- trabajo en el modulo de reportes
-- Carlos David Padilla Velásquez 20221003965  
-- Angie Rebeca Aguirre Rivera 20191007529, modulo Reportes

CREATE TABLE RP_TABLA_REPORTES (
   COD_REPORTE        BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL REPORTE'
  ,TIP_REPORTE        ENUM('VENTAS','INVENTARIO','FINANCIERO','GENERAL') NOT NULL COMMENT 'TIPO DE REPORTE'
  ,FEC_EMISION        DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE EMISION'
  ,FEC_PERIODO_DESDE DATE                   COMMENT 'FECHA INICIAL DEL PERIODO'
  ,FEC_PERIODO_HASTA DATE                   COMMENT 'FECHA FINAL DEL PERIODO'
  ,OBS_REPORTE        TEXT                  COMMENT 'OBSERVACIONES DEL REPORTE'
  ,USR_REGISTRO      VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO      DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPTABLREPO PRIMARY KEY (COD_REPORTE)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RP_GANANCIAS (
   COD_GANANCIA  BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA GANANCIA'
  ,COD_EVENTO    BIGINT NOT NULL    COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,MON_INGRESOS  DECIMAL(10,2)      COMMENT 'TOTAL DE INGRESOS'
  ,MON_COSTOS    DECIMAL(10,2)      COMMENT 'TOTAL DE COSTOS'
  ,MON_UTILIDAD  DECIMAL(10,2)      COMMENT 'UTILIDAD NETA'
  ,FEC_CIERRE    DATE               COMMENT 'FECHA DE CIERRE'
  ,USR_REGISTRO  VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO  DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPGANANCIA PRIMARY KEY (COD_GANANCIA)
  ,CONSTRAINT FK_RPGANANCIA_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RP_REPORTE_INVENTARIO (
   COD_REP_INVENTARIO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL REPORTE'
  ,COD_ITEM            BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL ITEM'
  ,COD_EVENTO          BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,CAN_UTILIZADA       INT                 COMMENT 'CANTIDAD UTILIZADA'
  ,DES_ESTADO_FINAL    VARCHAR(50)         COMMENT 'ESTADO FINAL DEL ITEM'
  ,OBS_NOTAS           TEXT                COMMENT 'NOTAS ADICIONALES'
  ,USR_REGISTRO        VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO        DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPREPINVEN PRIMARY KEY (COD_REP_INVENTARIO)
  ,CONSTRAINT FK_RREPINVEN_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO)
  ,CONSTRAINT FK_RREPINVEN_ITEM   FOREIGN KEY (COD_ITEM)   REFERENCES IN_INVENTARIO_ITEM(COD_ITEM)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RP_COSTOS_OPERATIVOS (
   COD_COSTO          BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL COSTO'
  ,COD_EVENTO         BIGINT NOT NULL   COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,COD_REPORTE        BIGINT            COMMENT 'LLAVE FORANEA DEL REPORTE'
  ,COD_PROVEEDOR      BIGINT            COMMENT 'LLAVE FORANEA DEL PROVEEDOR (PA_PROVEEDORES)'
  ,IND_CATEGORIA      ENUM('PERSONAL','LOGISTICA','MARKETING','EQUIPAMIENTO','SERVICIOS','OTROS') NOT NULL COMMENT 'CATEGORIA DEL COSTO'
  ,DES_COSTO          VARCHAR(255)      COMMENT 'DESCRIPCION DEL COSTO'
  ,MON_PRESUPUESTADO  DECIMAL(10,2) NOT NULL COMMENT 'MONTO PRESUPUESTADO'
  ,MON_REAL           DECIMAL(10,2) NOT NULL COMMENT 'MONTO REAL'
  ,OBS_COSTO          TEXT              COMMENT 'OBSERVACIONES'
  ,USR_REGISTRO       VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO       DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPCOSTOPER PRIMARY KEY (COD_COSTO)
  ,CONSTRAINT FK_RPCOSTOPER_EVENTO     FOREIGN KEY (COD_EVENTO)     REFERENCES VE_EVENTOS(COD_EVENTO)
  ,CONSTRAINT FK_RPCOSTOPER_REPORTE    FOREIGN KEY (COD_REPORTE)    REFERENCES RP_TABLA_REPORTES(COD_REPORTE)
  ,CONSTRAINT FK_RPCOSTOPER_PROVEEDOR  FOREIGN KEY (COD_PROVEEDOR) REFERENCES PA_PROVEEDORES(COD_PROVEEDOR) ON DELETE SET NULL
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;



-- PROCEDIMIENTOS MODULO DE PERSONAS
-- TODOS LOS MIEMBROS DEL EQUIPO ASIGNADOS A TRABAJAR EN ESTE MODULO
-- 3 PROCEDIMIENTOS
-- INSERT
-- UPDATE/SOFT DELETE
-- SELECT

-- PROCEDIMIENTO PARA INSERTAR A LAS TABLAS DEL MODULO PERSONAS 
-- FILTRADO POR MEDIO DE IFS ANIDADOS



DELIMITER $$
CREATE PROCEDURE SP_INSERT_PERSONAS(
    IN PV_ACCION VARCHAR(50),

    -- PERSONAS
    IN PV_DNI VARCHAR(255),
    IN PV_PRIMER_NOMBRE VARCHAR(255),
    IN PV_SEGUNDO_NOMBRE VARCHAR(255),
    IN PV_APELLIDO VARCHAR(255),
    IN PV_SEXO ENUM('M','F','O','D'),
    IN PV_EST_CIVIL ENUM('S','C','V'),
    IN PI_EDAD TINYINT,
    IN PV_TIP_PERSONA ENUM('N','J'),

    -- TELEFONOS
    IN PI_NUM_AREA SMALLINT,
    IN PI_NUM_TELEFONO INT,
    IN PV_TIP_TELEFONO ENUM('C','O','P'),

    -- CORREOS
    IN PV_USUARIO_CORREO VARCHAR(200),
    IN PV_SERVIDOR_CORREO VARCHAR(200),
    IN PV_TIP_CORREO ENUM('P','O'),

    -- TIPO USUARIO
    IN PV_NOM_TIPO VARCHAR(255),
    IN PV_DES_TIPO VARCHAR(2000),

    -- USUARIOS
    IN PI_COD_PERSONA BIGINT,
    IN PI_COD_TIPO_USR BIGINT,
    IN PV_NOMBRE VARCHAR(255),
    IN PV_CLAVE VARCHAR(2000),
    IN PV_TOKEN VARCHAR(6),
    IN PV_IND_USR ENUM('1','0'),
    IN PV_IND_PRIMER_ING ENUM('1','0'),

    -- TIPO CLIENTE
    IN PV_NOM_TIPO_CLI VARCHAR(255),
    IN PV_DES_TIPO_CLI VARCHAR(255),
    IN PV_IND_TIPO_CLI ENUM('1','0'),

    -- CLIENTES
    IN PI_COD_TIPO_CLI BIGINT,
    IN PV_NOM_EMPRESA VARCHAR(255),
    IN PV_IND_CLIENTE ENUM('1','0'),

    -- EMPLEADOS
    IN PV_CARGO VARCHAR(100),
    IN PD_FEC_CONTRATACION DATE,
    IN PM_SALARIO DECIMAL(10,2),

    -- PROVEEDORES
    IN PV_EMPRESA_PROV VARCHAR(150),
    IN PV_CATEGORIA_SERVICIO VARCHAR(100),

    -- AUDITORIA
    IN PV_USR_INGRESO VARCHAR(255)

)
BEGIN
START TRANSACTION;

IF PV_ACCION='INS_PERSONA' THEN
    INSERT INTO PA_PERSONAS
    (
        DNI,
        PRIMER_NOMBRE,
        SEGUNDO_NOMBRE,
        APELLIDO,
        SEXO,
        EST_CIVIL,
        EDAD,
        TIP_PERSONA,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PV_DNI,
        PV_PRIMER_NOMBRE,
        PV_SEGUNDO_NOMBRE,
        PV_APELLIDO,
        PV_SEXO,
        PV_EST_CIVIL,
        PI_EDAD,
        PV_TIP_PERSONA,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_TELEFONO' THEN
    INSERT INTO PA_TELEFONOS
    (
        NUM_AREA,
        NUM_TELEFONO,
        TIP_TELEFONO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_NUM_AREA,
        PI_NUM_TELEFONO,
        PV_TIP_TELEFONO,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_REL_PERSONA_TELEFONO' THEN
    INSERT INTO REL_PERSONAS_TELEFONOS
    (
        COD_PERSONA,
        COD_TELEFONO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_USR,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_CORREO' THEN
    INSERT INTO PA_CORREOS
    (
        USUARIO_CORREO,
        SERVIDOR_CORREO,
        TIP_CORREO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PV_USUARIO_CORREO,
        PV_SERVIDOR_CORREO,
        PV_TIP_CORREO,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_REL_PERSONA_CORREO' THEN
    INSERT INTO REL_PERSONAS_CORREOS
    (
        COD_PERSONA,
        COD_CORREO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_USR,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_TIPO_USUARIO' THEN
    INSERT INTO PA_TIPO_USUARIOS
    (
        NOM_TIPO,
        DES_TIPO
    )
    VALUES
    (
        PV_NOM_TIPO,
        PV_DES_TIPO
    );

ELSEIF PV_ACCION='INS_USUARIO' THEN
    INSERT INTO USUARIOS
    (
        COD_PERSONA,
        COD_TIPO_USR,
        NOMBRE,
        CLAVE,
        TOKEN,
        IND_USR,
        IND_PRIMER_ING,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_USR,
        PV_NOMBRE,
        PV_CLAVE,
        PV_TOKEN,
        PV_IND_USR,
        PV_IND_PRIMER_ING,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_TIPO_CLIENTE' THEN
    INSERT INTO PA_TIPO_CLIENTES
    (
        NOM_TIPO_CLI,
        DES_TIPO_CLI,
        IND_TIPO_CLI,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PV_NOM_TIPO_CLI,
        PV_DES_TIPO_CLI,
        PV_IND_TIPO_CLI,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_CLIENTE' THEN
    INSERT INTO PA_CLIENTES
    (
        COD_PERSONA,
        COD_TIPO_CLI,
        NOM_EMPRESA,
        IND_CLIENTE,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_CLI,
        PV_NOM_EMPRESA,
        PV_IND_CLIENTE,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_EMPLEADO' THEN
    INSERT INTO PA_EMPLEADOS
    (
        COD_PERSONA,
        CARGO,
        FEC_CONTRATACION,
        SALARIO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PV_CARGO,
        PD_FEC_CONTRATACION,
        PM_SALARIO,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_PROVEEDOR' THEN
    INSERT INTO PA_PROVEEDORES
    (
        COD_PERSONA,
        EMPRESA,
        CATEGORIA_SERVICIO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PV_EMPRESA_PROV,
        PV_CATEGORIA_SERVICIO,
        PV_USR_INGRESO,
        NOW()
    );

END IF;
COMMIT;
END$$
DELIMITER ;

-- =============================================================================
-- MODULO PERSONAS - PROCEDIMIENTO ALMACENADO UPDATE Y SOFT DELETE
-- FILTRADO POR MEDIO DE IFS ANIDADOS
-- =============================================================================

DELIMITER $$
CREATE PROCEDURE UPD_PERSONAS (
 IN PV_ACCION            VARCHAR(20),    
 IN PI_COD_PERSONA       BIGINT,
 IN PV_DNI               VARCHAR(255),
 IN PV_PRIMER_NOMBRE     VARCHAR(255),
 IN PV_SEGUNDO_NOMBRE    VARCHAR(255),
 IN PV_APELLIDO          VARCHAR(255),
 IN PC_SEXO              ENUM('M','F','O','D'),
 IN PC_EST_CIVIL         ENUM('S','C','V'),
 IN PI_EDAD              TINYINT,
 IN PI_NUM_AREA_CEL      SMALLINT,
 IN PI_NUM_TELEFONO_CEL  INT,
 IN PI_NUM_AREA_OFI      SMALLINT,
 IN PI_NUM_TELEFONO_OFI  INT,
 IN PV_USUARIO_CORREO    VARCHAR(200),
 IN PV_SERVIDOR_CORREO   VARCHAR(200),
 IN PV_NOMBRE_USR        VARCHAR(255),
 IN PV_CLAVE             VARCHAR(2000),
 IN PV_TOKEN             VARCHAR(6),
 IN PC_IND_USR           ENUM('1','0'),
 IN PC_IND_PRIMER_ING    ENUM('1','0'),
 IN PV_NOM_EMPRESA_CLI   VARCHAR(255),
 IN PC_IND_CLIENTE       ENUM('1','0'),
 IN PV_CARGO             VARCHAR(100),
 IN PD_FEC_CONTRATACION  DATE,
 IN PN_SALARIO           DECIMAL(10,2),
 IN PV_EMPRESA_PROV      VARCHAR(150),
 IN PV_CATEGORIA_SERV    VARCHAR(100),
 IN PV_USR_INGRESO       VARCHAR(255))
BEGIN
START TRANSACTION;

/* =============================================================================
   UPDATE
   ============================================================================= */
IF PV_ACCION = 'UPDATE' THEN

    
    IF PV_SEGUNDO_NOMBRE IS NULL THEN
      UPDATE PA_PERSONAS
      SET DNI            = IFNULL(PV_DNI, DNI),
          PRIMER_NOMBRE  = IFNULL(PV_PRIMER_NOMBRE, PRIMER_NOMBRE),
          APELLIDO       = IFNULL(PV_APELLIDO, APELLIDO),
          SEXO           = IFNULL(PC_SEXO, SEXO),
          EST_CIVIL      = IFNULL(PC_EST_CIVIL, EST_CIVIL),
          EDAD           = IFNULL(PI_EDAD, EDAD),
          USR_INGRESO    = PV_USR_INGRESO,
          FEC_INGRESO    = NOW()
      WHERE COD_PERSONA  = PI_COD_PERSONA;
    ELSE
      UPDATE PA_PERSONAS
      SET DNI            = IFNULL(PV_DNI, DNI),
          PRIMER_NOMBRE  = IFNULL(PV_PRIMER_NOMBRE, PRIMER_NOMBRE),
          SEGUNDO_NOMBRE = PV_SEGUNDO_NOMBRE,
          APELLIDO       = IFNULL(PV_APELLIDO, APELLIDO),
          SEXO           = IFNULL(PC_SEXO, SEXO),
          EST_CIVIL      = IFNULL(PC_EST_CIVIL, EST_CIVIL),
          EDAD           = IFNULL(PI_EDAD, EDAD),
          USR_INGRESO    = PV_USR_INGRESO,
          FEC_INGRESO    = NOW()
      WHERE COD_PERSONA  = PI_COD_PERSONA;
    END IF;

    
    SELECT @COD_TELCEL :=  t.COD_TELEFONO
                           from REL_PERSONAS_TELEFONOS r, PA_TELEFONOS t
                           where r.COD_TELEFONO = t.COD_TELEFONO
                           and r.COD_PERSONA = PI_COD_PERSONA
                           and t.TIP_TELEFONO = 'C';

    IF PI_NUM_AREA_CEL IS NOT NULL AND PI_NUM_TELEFONO_CEL IS NOT NULL THEN
      UPDATE PA_TELEFONOS
      SET NUM_AREA     = PI_NUM_AREA_CEL,
          NUM_TELEFONO = PI_NUM_TELEFONO_CEL,
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_TELEFONO = @COD_TELCEL;
    END IF;

    
    SELECT @COD_TELOFI :=  t.COD_TELEFONO
                           from REL_PERSONAS_TELEFONOS r, PA_TELEFONOS t
                           where r.COD_TELEFONO = t.COD_TELEFONO
                           and r.COD_PERSONA = PI_COD_PERSONA
                           and t.TIP_TELEFONO = 'O';

    IF PI_NUM_AREA_OFI IS NOT NULL AND PI_NUM_TELEFONO_OFI IS NOT NULL THEN
      UPDATE PA_TELEFONOS
      SET NUM_AREA     = PI_NUM_AREA_OFI,
          NUM_TELEFONO = PI_NUM_TELEFONO_OFI,
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_TELEFONO = @COD_TELOFI;
    END IF;

    
    SELECT @COD_CORREO :=  c.COD_CORREO
                           from REL_PERSONAS_CORREOS r, PA_CORREOS c
                           where r.COD_CORREO = c.COD_CORREO
                           and r.COD_PERSONA = PI_COD_PERSONA;

    IF PV_USUARIO_CORREO IS NOT NULL AND PV_SERVIDOR_CORREO IS NOT NULL THEN
      UPDATE PA_CORREOS
      SET USUARIO_CORREO  = PV_USUARIO_CORREO,
          SERVIDOR_CORREO = PV_SERVIDOR_CORREO,
          USR_INGRESO     = PV_USR_INGRESO,
          FEC_INGRESO     = NOW()
      WHERE COD_CORREO    = @COD_CORREO;
    END IF;

    
    SELECT @COD_USUARIO :=  u.COD_USUARIO
                            from USUARIOS u
                            where u.COD_PERSONA = PI_COD_PERSONA;

    IF PV_NOMBRE_USR IS NOT NULL THEN
      IF PV_CLAVE IS NOT NULL THEN
        UPDATE USUARIOS
        SET NOMBRE         = PV_NOMBRE_USR,
            CLAVE          = PV_CLAVE,
            TOKEN          = IFNULL(PV_TOKEN, TOKEN),
            IND_USR        = IFNULL(PC_IND_USR, IND_USR),
            IND_PRIMER_ING = IFNULL(PC_IND_PRIMER_ING, IND_PRIMER_ING),
            USR_INGRESO    = PV_USR_INGRESO,
            FEC_INGRESO    = NOW()
        WHERE COD_USUARIO  = @COD_USUARIO;
      ELSE
        UPDATE USUARIOS
        SET NOMBRE         = PV_NOMBRE_USR,
            TOKEN          = IFNULL(PV_TOKEN, TOKEN),
            IND_USR        = IFNULL(PC_IND_USR, IND_USR),
            IND_PRIMER_ING = IFNULL(PC_IND_PRIMER_ING, IND_PRIMER_ING),
            USR_INGRESO    = PV_USR_INGRESO,
            FEC_INGRESO    = NOW()
        WHERE COD_USUARIO  = @COD_USUARIO;
      END IF;
    END IF;


    SELECT @COD_CLIENTE :=  cl.COD_CLIENTE
                            from PA_CLIENTES cl
                            where cl.COD_PERSONA = PI_COD_PERSONA;

    IF PV_NOM_EMPRESA_CLI IS NOT NULL THEN
      UPDATE PA_CLIENTES
      SET NOM_EMPRESA  = PV_NOM_EMPRESA_CLI,
          IND_CLIENTE  = IFNULL(PC_IND_CLIENTE, IND_CLIENTE),
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_CLIENTE = @COD_CLIENTE;
    ELSEIF PC_IND_CLIENTE IS NOT NULL THEN
      UPDATE PA_CLIENTES
      SET IND_CLIENTE  = PC_IND_CLIENTE,
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_CLIENTE = @COD_CLIENTE;
    END IF;

    
    SELECT @COD_EMPLEADO :=  e.COD_EMPLEADO
                             from PA_EMPLEADOS e
                             where e.COD_PERSONA = PI_COD_PERSONA;

    IF PV_CARGO IS NOT NULL THEN
      UPDATE PA_EMPLEADOS
      SET CARGO            = PV_CARGO,
          FEC_CONTRATACION = IFNULL(PD_FEC_CONTRATACION, FEC_CONTRATACION),
          SALARIO          = IFNULL(PN_SALARIO, SALARIO),
          USR_INGRESO      = PV_USR_INGRESO,
          FEC_INGRESO      = NOW()
      WHERE COD_EMPLEADO   = @COD_EMPLEADO;
    ELSEIF PN_SALARIO IS NOT NULL THEN
      UPDATE PA_EMPLEADOS
      SET SALARIO          = PN_SALARIO,
          FEC_CONTRATACION = IFNULL(PD_FEC_CONTRATACION, FEC_CONTRATACION),
          USR_INGRESO      = PV_USR_INGRESO,
          FEC_INGRESO      = NOW()
      WHERE COD_EMPLEADO   = @COD_EMPLEADO;
    END IF;

    
    SELECT @COD_PROVEEDOR :=  p.COD_PROVEEDOR
                              from PA_PROVEEDORES p
                              where p.COD_PERSONA = PI_COD_PERSONA;

    IF PV_EMPRESA_PROV IS NOT NULL THEN
      UPDATE PA_PROVEEDORES
      SET EMPRESA            = PV_EMPRESA_PROV,
          CATEGORIA_SERVICIO = IFNULL(PV_CATEGORIA_SERV, CATEGORIA_SERVICIO),
          USR_INGRESO        = PV_USR_INGRESO,
          FEC_INGRESO        = NOW()
      WHERE COD_PROVEEDOR    = @COD_PROVEEDOR;
    END IF;

/* =============================================================================
   SOFT DELETE
   ============================================================================= */
ELSEIF PV_ACCION = 'SOFT_DELETE' THEN

    
    UPDATE USUARIOS
    SET IND_USR     = '0',               -- Cambia de activo '1' a inactivo '0'
        USR_INGRESO = PV_USR_INGRESO,
        FEC_INGRESO = NOW()
    WHERE COD_PERSONA = PI_COD_PERSONA;
    

END IF;

COMMIT;
END$$
DELIMITER ;

-- PROCEDIMIENTO DE SELECT MODULO DE PERSONAS
-- FILTRADO POR IFS ANIDADOS
-- SP_PA_SELECT

DELIMITER $$
CREATE PROCEDURE SP_PA_SELECT(
    IN  pv_accion          VARCHAR(255)
   ,IN  pi_cod_persona     BIGINT
   ,IN  pi_cod_telefono    BIGINT
   ,IN  pi_cod_rel_pertel  BIGINT
   ,IN  pi_cod_correo      BIGINT
   ,IN  pi_cod_rel_percor  BIGINT
   ,IN  pi_cod_tipo_usr    BIGINT
   ,IN  pi_cod_usuario     BIGINT
   ,IN  pi_cod_tipo_cli    BIGINT
   ,IN  pi_cod_cliente     BIGINT
   ,IN  pi_cod_empleado    BIGINT
   ,IN  pi_cod_proveedor   BIGINT
)
BEGIN

    START TRANSACTION;

    IF pv_accion = 'SEL_PA_PERSONAS' THEN

        SELECT
             COD_PERSONA
            ,DNI
            ,PRIMER_NOMBRE
            ,SEGUNDO_NOMBRE
            ,APELLIDO
            ,SEXO
            ,EST_CIVIL
            ,EDAD
            ,TIP_PERSONA
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_PERSONAS
        WHERE
            (pi_cod_persona IS NULL OR COD_PERSONA = pi_cod_persona);

    ELSEIF pv_accion = 'SEL_PA_TELEFONOS' THEN

        SELECT
             COD_TELEFONO
            ,NUM_AREA
            ,NUM_TELEFONO
            ,TIP_TELEFONO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_TELEFONOS
        WHERE
            (pi_cod_telefono IS NULL OR COD_TELEFONO = pi_cod_telefono);

    ELSEIF pv_accion = 'SEL_REL_PERSONAS_TELEFONOS' THEN

        SELECT
             COD_REL_PERTEL
            ,COD_PERSONA
            ,COD_TELEFONO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            REL_PERSONAS_TELEFONOS
        WHERE
            (pi_cod_rel_pertel IS NULL OR COD_REL_PERTEL = pi_cod_rel_pertel)
        AND (pi_cod_persona    IS NULL OR COD_PERSONA    = pi_cod_persona)
        AND (pi_cod_telefono   IS NULL OR COD_TELEFONO   = pi_cod_telefono);

    ELSEIF pv_accion = 'SEL_PA_CORREOS' THEN

        SELECT
             COD_CORREO
            ,USUARIO_CORREO
            ,SERVIDOR_CORREO
            ,TIP_CORREO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_CORREOS
        WHERE
            (pi_cod_correo IS NULL OR COD_CORREO = pi_cod_correo);

    ELSEIF pv_accion = 'SEL_REL_PERSONAS_CORREOS' THEN

        SELECT
             COD_REL_PERCOR
            ,COD_PERSONA
            ,COD_CORREO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            REL_PERSONAS_CORREOS
        WHERE
            (pi_cod_rel_percor IS NULL OR COD_REL_PERCOR = pi_cod_rel_percor)
        AND (pi_cod_persona    IS NULL OR COD_PERSONA    = pi_cod_persona)
        AND (pi_cod_correo     IS NULL OR COD_CORREO     = pi_cod_correo);

    ELSEIF pv_accion = 'SEL_PA_TIPO_USUARIOS' THEN

        SELECT
             COD_TIPO_USR
            ,NOM_TIPO
            ,DES_TIPO
        FROM
            PA_TIPO_USUARIOS
        WHERE
            (pi_cod_tipo_usr IS NULL OR COD_TIPO_USR = pi_cod_tipo_usr);

    ELSEIF pv_accion = 'SEL_USUARIOS' THEN

        SELECT
             COD_USUARIO
            ,COD_PERSONA
            ,COD_TIPO_USR
            ,NOMBRE
            ,TOKEN
            ,IND_USR
            ,IND_PRIMER_ING
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            USUARIOS
        WHERE
            (pi_cod_usuario  IS NULL OR COD_USUARIO  = pi_cod_usuario)
        AND (pi_cod_persona  IS NULL OR COD_PERSONA  = pi_cod_persona)
        AND (pi_cod_tipo_usr IS NULL OR COD_TIPO_USR = pi_cod_tipo_usr);

    ELSEIF pv_accion = 'SEL_PA_TIPO_CLIENTES' THEN

        SELECT
             COD_TIPO_CLI
            ,NOM_TIPO_CLI
            ,DES_TIPO_CLI
            ,IND_TIPO_CLI
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_TIPO_CLIENTES
        WHERE
            (pi_cod_tipo_cli IS NULL OR COD_TIPO_CLI = pi_cod_tipo_cli);

    ELSEIF pv_accion = 'SEL_PA_CLIENTES' THEN

        SELECT
             COD_CLIENTE
            ,COD_PERSONA
            ,COD_TIPO_CLI
            ,NOM_EMPRESA
            ,IND_CLIENTE
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_CLIENTES
        WHERE
            (pi_cod_cliente  IS NULL OR COD_CLIENTE  = pi_cod_cliente)
        AND (pi_cod_persona  IS NULL OR COD_PERSONA  = pi_cod_persona)
        AND (pi_cod_tipo_cli IS NULL OR COD_TIPO_CLI = pi_cod_tipo_cli);

    ELSEIF pv_accion = 'SEL_PA_EMPLEADOS' THEN

        SELECT
             COD_EMPLEADO
            ,COD_PERSONA
            ,CARGO
            ,FEC_CONTRATACION
            ,SALARIO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_EMPLEADOS
        WHERE
            (pi_cod_empleado IS NULL OR COD_EMPLEADO = pi_cod_empleado)
        AND (pi_cod_persona  IS NULL OR COD_PERSONA  = pi_cod_persona);

    ELSEIF pv_accion = 'SEL_PA_PROVEEDORES' THEN

        SELECT
             COD_PROVEEDOR
            ,COD_PERSONA
            ,EMPRESA
            ,CATEGORIA_SERVICIO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_PROVEEDORES
        WHERE
            (pi_cod_proveedor IS NULL OR COD_PROVEEDOR = pi_cod_proveedor)
        AND (pi_cod_persona   IS NULL OR COD_PERSONA   = pi_cod_persona);

    END IF;

    COMMIT;

END $$
DELIMITER ;


-- procedimientos almacenados modulo de reservacion INSERT, UPDATE Y SOFT DELETE, SELEC * A TABLAS DEL MOULO
-- trabajo en el modulo de reservacion:
-- Jorge Alberto Maradiaga Molina 20152502011
-- Josue David Ortiz Ortiz 20231003161
-- PROCEDIMIENTO DE INSERT MODULO DE RESERVACION
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION

DELIMITER $$
CREATE PROCEDURE SP_RE_INSERT(
	IN  pv_accion           VARCHAR(255),
	IN  pv_nom_espacio      VARCHAR(100),
	IN  pi_can_capacidad    INT,
	IN  pv_tip_espacio      ENUM('SALON','AUDITORIO','AREA_EXTERIOR','SALA_REUNION'),
	IN  pv_ind_estado       ENUM('DISPONIBLE','MANTENIMIENTO','INACTIVO','PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA'),
	IN  pd_mon_precio_hora  DECIMAL(10,2),
	IN  pi_cod_espacio      INT,
	IN  pi_cod_cliente      BIGINT,
	IN  pi_cod_empleado     BIGINT,
	IN  pv_fec_inicio       DATETIME,
	IN  pv_fec_fin          DATETIME,
	IN  pv_des_notas        TEXT,
	IN  pv_usr_ingreso      VARCHAR(255),
	IN  pv_des_motivo       VARCHAR(200),
	IN  pi_cod_reservacion  INT,
	IN  pv_ind_estado_ant   ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA'),
	IN  pv_ind_estado_nue   ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA'),
	IN  pi_cod_persona_cam  BIGINT
)
BEGIN

    START TRANSACTION;

    IF pv_accion = 'INS_RE_ESPACIO' THEN

        INSERT INTO RE_ESPACIO (
			NOM_ESPACIO,
            CAN_CAPACIDAD,
            TIP_ESPACIO,
            IND_ESTADO,
            MON_PRECIO_HORA
        ) VALUES (
			pv_nom_espacio,
            pi_can_capacidad,
            pv_tip_espacio,
            pv_ind_estado,
            pd_mon_precio_hora
        );

    ELSEIF pv_accion = 'INS_RE_RESERVACION' THEN

        INSERT INTO RE_RESERVACION (
			COD_ESPACIO,
			COD_CLIENTE,
			COD_EMPLEADO,
			FEC_INICIO,
			FEC_FIN,
			IND_ESTADO,
			DES_NOTAS,
			USR_INGRESO
        ) VALUES (
			pi_cod_espacio,
			pi_cod_cliente,
			pi_cod_empleado,
			pv_fec_inicio,
			pv_fec_fin,
			pv_ind_estado,
			pv_des_notas,
			pv_usr_ingreso
        );

    ELSEIF pv_accion = 'INS_RE_ESPACIO_OCUPADO' THEN

        INSERT INTO RE_ESPACIO_OCUPADO (
			COD_ESPACIO,
			FEC_INICIO,
            FEC_FIN,
			DES_MOTIVO,
			USR_INGRESO
        ) VALUES (
			pi_cod_espacio,
			IFNULL(pv_fec_inicio, NOW()),
			pv_fec_fin,
			pv_des_motivo,
			pv_usr_ingreso
        );

    ELSEIF pv_accion = 'INS_RE_HISTORIAL_RESERVACION' THEN

        INSERT INTO RE_HISTORIAL_RESERVACION (
			COD_RESERVACION,
            IND_ESTADO_ANT,
            IND_ESTADO_NUE,
            COD_PERSONA_CAM
        ) VALUES (
			pi_cod_reservacion,
            pv_ind_estado_ant,
            pv_ind_estado_nue,
            pi_cod_persona_cam
        );

    END IF;

    COMMIT;

END $$
DELIMITER ;

-- PROCEDIMIENTO DE UPDATE/SOFT DELETE (CAMBIO DE ESTADO) MODULO DE RESERVACION
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION

DELIMITER $$
CREATE PROCEDURE SP_RE_UPDATE(
	IN  pv_accion           VARCHAR(255),
	IN  pi_cod_espacio      INT,
	IN  pv_nom_espacio      VARCHAR(100),
	IN  pi_can_capacidad    INT,
	IN  pv_tip_espacio      ENUM('SALON','AUDITORIO','AREA_EXTERIOR','SALA_REUNION'),
	IN  pv_ind_estado       ENUM('DISPONIBLE','MANTENIMIENTO','INACTIVO','PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA'),
	IN  pd_mon_precio_hora  DECIMAL(10,2),
	IN  pi_cod_reservacion  INT,
	IN  pi_cod_cliente      BIGINT,
	IN  pi_cod_empleado     BIGINT,
	IN  pv_fec_inicio       DATETIME,
	IN  pv_fec_fin          DATETIME,
	IN  pv_des_notas        TEXT,
	IN  pi_cod_espa_ocup    INT,
	IN  pv_des_motivo       VARCHAR(200)
)
BEGIN
    START TRANSACTION;
    IF pv_accion = 'UPD_RE_ESPACIO' THEN
        UPDATE RE_ESPACIO
        SET
			NOM_ESPACIO     = pv_nom_espacio,
            CAN_CAPACIDAD   = pi_can_capacidad,
            TIP_ESPACIO     = pv_tip_espacio,
            IND_ESTADO      = pv_ind_estado,
            MON_PRECIO_HORA = pd_mon_precio_hora
        WHERE
            COD_ESPACIO = pi_cod_espacio;
    ELSEIF pv_accion = 'UPD_RE_RESERVACION' THEN
        UPDATE RE_RESERVACION
        SET
			COD_ESPACIO  = pi_cod_espacio,
            COD_CLIENTE  = pi_cod_cliente,
            COD_EMPLEADO = pi_cod_empleado,
            FEC_INICIO = IFNULL(pv_fec_inicio, NOW()),
            FEC_FIN      = pv_fec_fin,
            IND_ESTADO   = pv_ind_estado,
            DES_NOTAS    = pv_des_notas
        WHERE
            COD_RESERVACION = pi_cod_reservacion;
    ELSEIF pv_accion = 'UPD_RE_ESPACIO_OCUPADO' THEN
        UPDATE RE_ESPACIO_OCUPADO
        SET
			COD_ESPACIO = pi_cod_espacio,
            FEC_INICIO = IFNULL(pv_fec_inicio, NOW()),
            FEC_FIN     = pv_fec_fin,
            DES_MOTIVO  = pv_des_motivo
        WHERE
            COD_ESPA_OCUP = pi_cod_espa_ocup;
    ELSEIF pv_accion = 'UPD_RE_SOFT_DELETE_ESPACIO' THEN
        UPDATE RE_ESPACIO
        SET
            IND_ESTADO = pv_ind_estado
        WHERE
            COD_ESPACIO = pi_cod_espacio;
    ELSEIF pv_accion = 'UPD_RE_SOFT_DELETE_RESERVACION' THEN
        UPDATE RE_RESERVACION
        SET
            IND_ESTADO = pv_ind_estado
        WHERE
            COD_RESERVACION = pi_cod_reservacion;
    END IF;
    COMMIT;
END $$
DELIMITER ;

-- PROCEDIMIENTO DE SELECT * MODULO DE RESERVACION
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION

DELIMITER $$
CREATE PROCEDURE SP_RE_SELECT(
    IN  pv_accion           VARCHAR(255),
	IN  pi_cod_espacio      INT,
	IN  pi_cod_reservacion  INT,
	IN  pi_cod_espa_ocup    INT,
	IN  pi_csc_historial    INT
)
BEGIN

    START TRANSACTION;

    IF pv_accion = 'SEL_RE_ESPACIO' THEN

        SELECT
			COD_ESPACIO,
            NOM_ESPACIO,
            CAN_CAPACIDAD,
            TIP_ESPACIO,
            IND_ESTADO,
            MON_PRECIO_HORA
        FROM
            RE_ESPACIO
        WHERE
            (pi_cod_espacio IS NULL OR COD_ESPACIO = pi_cod_espacio);

    ELSEIF pv_accion = 'SEL_RE_RESERVACION' THEN

        SELECT
			COD_RESERVACION,
            COD_ESPACIO,
            COD_CLIENTE,
            COD_EMPLEADO,
            FEC_INICIO,
            FEC_FIN,
            IND_ESTADO,
            DES_NOTAS,
            USR_INGRESO,
            FEC_INGRESO
        FROM
            RE_RESERVACION
        WHERE
            (pi_cod_reservacion IS NULL OR COD_RESERVACION = pi_cod_reservacion);

    ELSEIF pv_accion = 'SEL_RE_ESPACIO_OCUPADO' THEN

        SELECT
			COD_ESPA_OCUP,
            COD_ESPACIO,
            FEC_INICIO,
            FEC_FIN,
            DES_MOTIVO,
            USR_INGRESO,
            FEC_INGRESO
        FROM
            RE_ESPACIO_OCUPADO
        WHERE
            (pi_cod_espa_ocup IS NULL OR COD_ESPA_OCUP = pi_cod_espa_ocup);

    ELSEIF pv_accion = 'SEL_RE_HISTORIAL_RESERVACION' THEN

        SELECT
			CSC_HISTORIAL,
            COD_RESERVACION,
            IND_ESTADO_ANT,
            IND_ESTADO_NUE,
            COD_PERSONA_CAM,
            FEC_ADICION
        FROM
            RE_HISTORIAL_RESERVACION
        WHERE
            (pi_csc_historial   IS NULL OR CSC_HISTORIAL   = pi_csc_historial)
        AND (pi_cod_reservacion  IS NULL OR COD_RESERVACION = pi_cod_reservacion);

    END IF;

    COMMIT;

END $$
DELIMITER ;

-- PROCEDIMIENTOS MODULO DE VENTAS

-- trabajo en el modulo de ventas:
-- Juan Carlos López Avila 20181033368
-- Jaziel Jafeth Funez Andino 20201003788

-- PROCEDIMIENTO DE INSERT MODULO DE VENTAS
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION

DELIMITER $$
CREATE PROCEDURE SP_INSERT_VENTAS(
    IN PV_ACCION VARCHAR(50),

    IN PI_COD_CATEGORIA BIGINT,
    IN PI_COD_CICLO_EVENTO INT,
    IN PI_COD_RESERVACION INT,
    IN PI_COD_EVENTO BIGINT,
    IN PI_COD_BOLETO BIGINT,
    IN PI_COD_CLIENTE BIGINT,
    IN PI_COD_VENTA BIGINT,

    IN PV_NOM_CATEGORIA VARCHAR(100),
    IN PV_DES_CATEGORIA TEXT,

    IN PV_NOM_CICLO VARCHAR(100),
    IN PV_DES_CICLO VARCHAR(255),
    IN PV_USR_INGRESO VARCHAR(255),

    IN PV_NOM_EVENTO VARCHAR(150),
    IN PV_DES_EVENTO TEXT,
    IN PD_FEC_EVENTO DATE,
    IN PT_HOR_EVENTO TIME,
    IN PV_DES_LUGAR VARCHAR(150),
    IN PI_NUM_CAPACIDAD INT,
    IN PV_IND_ESTADO ENUM('ACTIVO','CANCELADO','FINALIZADO'),

    IN PV_TIP_BOLETO ENUM('VIP','GENERAL','PREFERENCIAL','BACKSTAGE'),
    IN PN_MON_PRECIO DECIMAL(10,2),
    IN PI_NUM_DISPONIBLE INT,
    IN PV_DES_BOLETO TEXT,

    IN PN_MON_TOTAL DECIMAL(10,2),
    IN PV_METODO_PAGO ENUM('EFECTIVO','TARJETA','TRANSFERENCIA'),
    IN PV_ESTADO_VENTA ENUM('PAGADA','PENDIENTE','CANCELADA'),

    IN PI_CANTIDAD INT,
    IN PN_PRECIO_UNIT DECIMAL(10,2),
    IN PN_SUBTOTAL DECIMAL(10,2),

    IN PN_MON_PAGO DECIMAL(10,2),
    IN PV_REFERENCIA VARCHAR(100),
    IN PV_ESTADO_PAGO ENUM('APROBADO','PENDIENTE','RECHAZADO')
)
BEGIN
START TRANSACTION;

IF PV_ACCION='INS_CATEGORIA' THEN

    INSERT INTO VE_CATEGORIA_EVENTOS
    (
        NOM_CATEGORIA,
        DES_CATEGORIA
    )
    VALUES
    (
        PV_NOM_CATEGORIA,
        PV_DES_CATEGORIA
    );

ELSEIF PV_ACCION='INS_CICLO' THEN

    INSERT INTO VE_CICLO_EVENTO
    (
        NOM_CICLO,
        DES_CICLO,
        USR_INGRESO
    )
    VALUES
    (
        PV_NOM_CICLO,
        PV_DES_CICLO,
        PV_USR_INGRESO
    );

ELSEIF PV_ACCION='INS_EVENTO' THEN

    INSERT INTO VE_EVENTOS
    (
        COD_CATEGORIA,
        COD_CICLO_EVENTO,
        COD_RESERVACION,
        NOM_EVENTO,
        DES_EVENTO,
        FEC_EVENTO,
        HOR_EVENTO,
        DES_LUGAR,
        NUM_CAPACIDAD,
        IND_ESTADO
    )
    VALUES
    (
        PI_COD_CATEGORIA,
        PI_COD_CICLO_EVENTO,
        PI_COD_RESERVACION,
        PV_NOM_EVENTO,
        PV_DES_EVENTO,
        PD_FEC_EVENTO,
        PT_HOR_EVENTO,
        PV_DES_LUGAR,
        PI_NUM_CAPACIDAD,
        PV_IND_ESTADO
    );

ELSEIF PV_ACCION='INS_BOLETO' THEN

    INSERT INTO VE_BOLETOS
    (
        COD_EVENTO,
        TIP_BOLETO,
        MON_PRECIO,
        NUM_DISPONIBLE,
        DES_BOLETO
    )
    VALUES
    (
        PI_COD_EVENTO,
        PV_TIP_BOLETO,
        PN_MON_PRECIO,
        PI_NUM_DISPONIBLE,
        PV_DES_BOLETO
    );

ELSEIF PV_ACCION='INS_VENTA' THEN

    INSERT INTO VE_VENTAS
    (
        COD_CLIENTE,
        MON_TOTAL,
        IND_METODO_PAGO,
        IND_ESTADO_VENTA
    )
    VALUES
    (
        PI_COD_CLIENTE,
        PN_MON_TOTAL,
        PV_METODO_PAGO,
        PV_ESTADO_VENTA
    );

ELSEIF PV_ACCION='INS_DETALLE' THEN

    INSERT INTO VE_DETALLE_VENTAS
    (
        COD_VENTA,
        COD_BOLETO,
        NUM_CANTIDAD,
        MON_PRECIO_UNIT,
        MON_SUBTOTAL
    )
    VALUES
    (
        PI_COD_VENTA,
        PI_COD_BOLETO,
        PI_CANTIDAD,
        PN_PRECIO_UNIT,
        PN_SUBTOTAL
    );

ELSEIF PV_ACCION='INS_PAGO' THEN

    INSERT INTO VE_PAGOS
    (
        COD_VENTA,
        MON_PAGO,
        COD_REFERENCIA,
        IND_ESTADO_PAGO
    )
    VALUES
    (
        PI_COD_VENTA,
        PN_MON_PAGO,
        PV_REFERENCIA,
        PV_ESTADO_PAGO
    );

END IF;
COMMIT;
END$$
DELIMITER ;


-- =============================================================================
-- PROCEDIMIENTO UPDATE
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION
-- =============================================================================

DELIMITER $$
CREATE PROCEDURE SP_UPDATE_VENTAS
(
    IN PV_ACCION             VARCHAR(50),
    IN PI_COD_CATEGORIA      BIGINT,
    IN PV_NOM_CATEGORIA      VARCHAR(100),
    IN PV_DES_CATEGORIA      TEXT,
    IN PI_COD_CICLO_EVENTO   INT,
    IN PV_NOM_CICLO          VARCHAR(100),
    IN PV_DES_CICLO          VARCHAR(255),
    IN PV_IND_ACTIVO_CICLO   ENUM('1','0'),
    IN PI_COD_EVENTO         BIGINT,
    IN PI_COD_RESERVACION    INT,
    IN PV_NOM_EVENTO         VARCHAR(150),
    IN PV_DES_EVENTO         TEXT,
    IN PD_FEC_EVENTO         DATE,
    IN PT_HOR_EVENTO         TIME,
    IN PV_DES_LUGAR          VARCHAR(150),
    IN PI_NUM_CAPACIDAD      INT,
    IN PV_IND_ESTADO_EVENTO  ENUM('ACTIVO','CANCELADO','FINALIZADO'),
    IN PI_COD_BOLETO         BIGINT,
    IN PV_TIP_BOLETO         ENUM('VIP','GENERAL','PREFERENCIAL','BACKSTAGE'),
    IN PM_MON_PRECIO         DECIMAL(10,2),
    IN PI_NUM_DISPONIBLE     INT,
    IN PV_DES_BOLETO         TEXT,
    IN PI_COD_VENTA          BIGINT,
    IN PI_COD_CLIENTE        BIGINT,
    IN PM_MON_TOTAL          DECIMAL(10,2),
    IN PV_IND_METODO_PAGO    ENUM('EFECTIVO','TARJETA','TRANSFERENCIA'),
    IN PV_IND_ESTADO_VENTA   ENUM('PAGADA','PENDIENTE','CANCELADA'),
    IN PI_COD_DETALLE        BIGINT,
    IN PI_NUM_CANTIDAD       INT,
    IN PM_MON_PRECIO_UNIT    DECIMAL(10,2),
    IN PM_MON_SUBTOTAL       DECIMAL(10,2),
    IN PI_COD_PAGO           BIGINT,
    IN PM_MON_PAGO           DECIMAL(10,2),
    IN PV_COD_REFERENCIA     VARCHAR(100),
    IN PV_IND_ESTADO_PAGO    ENUM('APROBADO','PENDIENTE','RECHAZADO'),
    IN PV_IND_ACTIVO         ENUM('1','0')
)
BEGIN
START TRANSACTION;

    IF PV_ACCION='UPD_CATEGORIA' THEN
        UPDATE VE_CATEGORIA_EVENTOS
           SET NOM_CATEGORIA = IFNULL(PV_NOM_CATEGORIA, NOM_CATEGORIA),
               DES_CATEGORIA = IFNULL(PV_DES_CATEGORIA, DES_CATEGORIA),
               IND_ACTIVO    = IFNULL(PV_IND_ACTIVO,    IND_ACTIVO)
         WHERE COD_CATEGORIA = PI_COD_CATEGORIA;

    ELSEIF PV_ACCION='DEL_CATEGORIA' THEN
        UPDATE VE_CATEGORIA_EVENTOS
           SET IND_ACTIVO = '0'
         WHERE COD_CATEGORIA = PI_COD_CATEGORIA;

    ELSEIF PV_ACCION='UPD_CICLO' THEN
        UPDATE VE_CICLO_EVENTO
           SET NOM_CICLO  = IFNULL(PV_NOM_CICLO,        NOM_CICLO),
               DES_CICLO  = IFNULL(PV_DES_CICLO,        DES_CICLO),
               IND_ACTIVO = IFNULL(PV_IND_ACTIVO_CICLO, IND_ACTIVO)
         WHERE COD_CICLO_EVENTO = PI_COD_CICLO_EVENTO;

    ELSEIF PV_ACCION='DEL_CICLO' THEN
        UPDATE VE_CICLO_EVENTO
           SET IND_ACTIVO = '0'
         WHERE COD_CICLO_EVENTO = PI_COD_CICLO_EVENTO;

    ELSEIF PV_ACCION='UPD_EVENTO' THEN
        UPDATE VE_EVENTOS
           SET COD_CATEGORIA    = IFNULL(PI_COD_CATEGORIA,   COD_CATEGORIA),
               COD_CICLO_EVENTO = IFNULL(PI_COD_CICLO_EVENTO,COD_CICLO_EVENTO),
               COD_RESERVACION  = IFNULL(PI_COD_RESERVACION, COD_RESERVACION),
               NOM_EVENTO       = IFNULL(PV_NOM_EVENTO,      NOM_EVENTO),
               DES_EVENTO       = IFNULL(PV_DES_EVENTO,      DES_EVENTO),
               FEC_EVENTO       = IFNULL(PD_FEC_EVENTO,      FEC_EVENTO),
               HOR_EVENTO       = IFNULL(PT_HOR_EVENTO,      HOR_EVENTO),
               DES_LUGAR        = IFNULL(PV_DES_LUGAR,       DES_LUGAR),
               NUM_CAPACIDAD    = IFNULL(PI_NUM_CAPACIDAD,   NUM_CAPACIDAD),
               IND_ESTADO       = IFNULL(PV_IND_ESTADO_EVENTO,IND_ESTADO),
               IND_ACTIVO       = IFNULL(PV_IND_ACTIVO,      IND_ACTIVO)
         WHERE COD_EVENTO = PI_COD_EVENTO;

    ELSEIF PV_ACCION='DEL_EVENTO' THEN
        UPDATE VE_EVENTOS
           SET IND_ACTIVO = '0'
         WHERE COD_EVENTO = PI_COD_EVENTO;

    ELSEIF PV_ACCION='UPD_BOLETO' THEN
        UPDATE VE_BOLETOS
           SET COD_EVENTO     = IFNULL(PI_COD_EVENTO,     COD_EVENTO),
               TIP_BOLETO     = IFNULL(PV_TIP_BOLETO,     TIP_BOLETO),
               MON_PRECIO     = IFNULL(PM_MON_PRECIO,     MON_PRECIO),
               NUM_DISPONIBLE = IFNULL(PI_NUM_DISPONIBLE, NUM_DISPONIBLE),
               DES_BOLETO     = IFNULL(PV_DES_BOLETO,     DES_BOLETO),
               IND_ACTIVO     = IFNULL(PV_IND_ACTIVO,     IND_ACTIVO)
         WHERE COD_BOLETO = PI_COD_BOLETO;

    ELSEIF PV_ACCION='DEL_BOLETO' THEN
        UPDATE VE_BOLETOS
           SET IND_ACTIVO='0'
         WHERE COD_BOLETO = PI_COD_BOLETO;

    ELSEIF PV_ACCION='UPD_VENTA' THEN
        UPDATE VE_VENTAS
           SET COD_CLIENTE      = IFNULL(PI_COD_CLIENTE,     COD_CLIENTE),
               MON_TOTAL        = IFNULL(PM_MON_TOTAL,       MON_TOTAL),
               IND_METODO_PAGO  = IFNULL(PV_IND_METODO_PAGO, IND_METODO_PAGO),
               IND_ESTADO_VENTA = IFNULL(PV_IND_ESTADO_VENTA,IND_ESTADO_VENTA),
               IND_ACTIVO       = IFNULL(PV_IND_ACTIVO,      IND_ACTIVO)
         WHERE COD_VENTA = PI_COD_VENTA;

    ELSEIF PV_ACCION='DEL_VENTA' THEN
        UPDATE VE_VENTAS
           SET IND_ACTIVO='0'
         WHERE COD_VENTA = PI_COD_VENTA;

    ELSEIF PV_ACCION='UPD_DETALLE' THEN
        UPDATE VE_DETALLE_VENTAS
           SET COD_VENTA       = IFNULL(PI_COD_VENTA,       COD_VENTA),
               COD_BOLETO      = IFNULL(PI_COD_BOLETO,      COD_BOLETO),
               NUM_CANTIDAD    = IFNULL(PI_NUM_CANTIDAD,     NUM_CANTIDAD),
               MON_PRECIO_UNIT = IFNULL(PM_MON_PRECIO_UNIT, MON_PRECIO_UNIT),
               MON_SUBTOTAL    = IFNULL(PM_MON_SUBTOTAL,    MON_SUBTOTAL),
               IND_ACTIVO      = IFNULL(PV_IND_ACTIVO,      IND_ACTIVO)
         WHERE COD_DETALLE = PI_COD_DETALLE;

    ELSEIF PV_ACCION='DEL_DETALLE' THEN
        UPDATE VE_DETALLE_VENTAS
           SET IND_ACTIVO='0'
         WHERE COD_DETALLE = PI_COD_DETALLE;

    ELSEIF PV_ACCION='UPD_PAGO' THEN
        UPDATE VE_PAGOS
           SET COD_VENTA       = IFNULL(PI_COD_VENTA,        COD_VENTA),
               MON_PAGO        = IFNULL(PM_MON_PAGO,         MON_PAGO),
               COD_REFERENCIA  = IFNULL(PV_COD_REFERENCIA,   COD_REFERENCIA),
               IND_ESTADO_PAGO = IFNULL(PV_IND_ESTADO_PAGO,  IND_ESTADO_PAGO),
               IND_ACTIVO      = IFNULL(PV_IND_ACTIVO,       IND_ACTIVO)
         WHERE COD_PAGO = PI_COD_PAGO;

    ELSEIF PV_ACCION='DEL_PAGO' THEN
        UPDATE VE_PAGOS
           SET IND_ACTIVO='0'
         WHERE COD_PAGO = PI_COD_PAGO;

    END IF;

COMMIT;
END$$
DELIMITER ;

-- =============================================================================
-- PROCEDIMIENTO SELECT
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION
-- =============================================================================

DELIMITER $$
CREATE PROCEDURE SP_SELECT_VENTAS(
    IN PV_ACCION VARCHAR(50)
)
BEGIN

    IF PV_ACCION = 'SEL_CATEGORIA' THEN

        SELECT *
        FROM VE_CATEGORIA_EVENTOS
        WHERE IND_ACTIVO = '1';

    ELSEIF PV_ACCION = 'SEL_CICLO' THEN

        SELECT *
        FROM VE_CICLO_EVENTO
        WHERE IND_ACTIVO = '1';

    ELSEIF PV_ACCION = 'SEL_EVENTO' THEN

        SELECT
             E.COD_EVENTO
            ,E.NOM_EVENTO
            ,C.NOM_CATEGORIA
            ,CE.NOM_CICLO
            ,E.FEC_EVENTO
            ,E.HOR_EVENTO
            ,E.DES_LUGAR
            ,E.IND_ESTADO
        FROM VE_EVENTOS E
        INNER JOIN VE_CATEGORIA_EVENTOS C
            ON E.COD_CATEGORIA = C.COD_CATEGORIA
        INNER JOIN VE_CICLO_EVENTO CE
            ON E.COD_CICLO_EVENTO = CE.COD_CICLO_EVENTO
        WHERE E.IND_ACTIVO = '1'
          AND C.IND_ACTIVO = '1'
          AND CE.IND_ACTIVO = '1';

    ELSEIF PV_ACCION = 'SEL_BOLETO' THEN

        SELECT *
        FROM VE_BOLETOS
        WHERE IND_ACTIVO = '1';

    ELSEIF PV_ACCION = 'SEL_VENTA' THEN

        SELECT *
        FROM VE_VENTAS
        WHERE IND_ACTIVO = '1';

    ELSEIF PV_ACCION = 'SEL_DETALLE' THEN

        SELECT *
        FROM VE_DETALLE_VENTAS
        WHERE IND_ACTIVO = '1';

    ELSEIF PV_ACCION = 'SEL_PAGO' THEN

        SELECT *
        FROM VE_PAGOS
        WHERE IND_ACTIVO = '1';

    END IF;

END$$
DELIMITER ;

-- =============================================================================
-- STORED PROCEDURES MÓDULO INVENTARIO (IN)
-- =============================================================================

-- trabajo en el modulo de inventario:
-- Cindy Michelle Osorto González 20211001885
-- Joel fernando valladares CRUZ 20211024825



DELIMITER $$
CREATE PROCEDURE SEL_ALL_INVENTARIO(
    IN pi_cod_item       BIGINT,
    IN pi_cod_categoria  BIGINT,
    IN pi_cod_almacen    BIGINT,
    IN pi_cod_evento     BIGINT
)
BEGIN
    -- Ítems con nombre de categoría y almacén
    SELECT
         i.COD_ITEM
        ,i.NOM_ITEM
        ,i.DES_ITEM
        ,i.COD_CATEGORIA
        ,c.NOM_CATEGORIA
        ,i.COD_ALMACEN
        ,a.NOM_ALMACEN
        ,i.CAN_TOTAL
        ,i.CAN_DISPONIBLE
        ,i.IND_ESTADO
        ,i.COD_ITEM_UNICO
        ,i.IMG_FOTO_URL
        ,i.FEC_ADQUISICION
        ,i.MON_COSTO
        ,i.USR_REGISTRO
        ,i.FEC_REGISTRO
    FROM IN_INVENTARIO_ITEM i
    LEFT JOIN IN_CATEGORIAS_INVENTARIO c ON i.COD_CATEGORIA = c.COD_CATEGORIA
    LEFT JOIN IN_ALMACENES             a ON i.COD_ALMACEN   = a.COD_ALMACEN
    WHERE (pi_cod_item      IS NULL OR i.COD_ITEM     = pi_cod_item)
    AND   (pi_cod_categoria IS NULL OR i.COD_CATEGORIA = pi_cod_categoria)
    AND   (pi_cod_almacen   IS NULL OR i.COD_ALMACEN   = pi_cod_almacen)
    AND   i.IND_ESTADO <> 'BAJA';

    -- Categorías activas
    SELECT
         COD_CATEGORIA
        ,NOM_CATEGORIA
        ,DES_CATEGORIA
        ,DES_ICONO
        ,IND_ACTIVA
        ,USR_REGISTRO
        ,FEC_REGISTRO
    FROM IN_CATEGORIAS_INVENTARIO
    WHERE IND_ACTIVA = TRUE
    AND   (pi_cod_categoria IS NULL OR COD_CATEGORIA = pi_cod_categoria);

    -- Almacenes activos
    SELECT
         COD_ALMACEN
        ,NOM_ALMACEN
        ,DIR_UBICACION
        ,COD_EMPLEADO
        ,CAN_CAPACIDAD
        ,IND_ACTIVO
        ,USR_REGISTRO
        ,FEC_REGISTRO
    FROM IN_ALMACENES
    WHERE IND_ACTIVO = TRUE
    AND   (pi_cod_almacen IS NULL OR COD_ALMACEN = pi_cod_almacen);

    -- Reservas de inventario
    SELECT
         r.COD_RESERVA
        ,r.COD_EVENTO
        ,r.COD_ITEM
        ,i.NOM_ITEM
        ,r.CAN_RESERVADA
        ,r.FEC_INICIO_RESERVA
        ,r.FEC_FIN_RESERVA
        ,r.IND_ESTADO_RESERVA
        ,r.NOM_SOLICITANTE
        ,r.DES_NOTAS
        ,r.USR_REGISTRO
        ,r.FEC_REGISTRO
    FROM IN_RESERVAS_INVENTARIO r
    LEFT JOIN IN_INVENTARIO_ITEM i ON r.COD_ITEM = i.COD_ITEM
    WHERE (pi_cod_evento IS NULL OR r.COD_EVENTO = pi_cod_evento)
    AND   (pi_cod_item   IS NULL OR r.COD_ITEM   = pi_cod_item);

    -- Asignaciones a evento
    SELECT
         ae.COD_ASIGNACION
        ,ae.COD_EVENTO
        ,ae.COD_ITEM
        ,i.NOM_ITEM
        ,ae.CAN_ASIGNADA
        ,ae.FEC_SALIDA
        ,ae.FEC_RETORNO
        ,ae.IND_ESTADO
        ,ae.IND_CONDICION
        ,ae.NOM_RESPONSABLE
        ,ae.DES_OBSERVACIONES
        ,ae.USR_REGISTRO
        ,ae.FEC_REGISTRO
    FROM IN_ASIGNACION_EVENTO ae
    LEFT JOIN IN_INVENTARIO_ITEM i ON ae.COD_ITEM = i.COD_ITEM
    WHERE (pi_cod_evento IS NULL OR ae.COD_EVENTO = pi_cod_evento)
    AND   (pi_cod_item   IS NULL OR ae.COD_ITEM   = pi_cod_item);

END$$
DELIMITER ;

-- ─────────────────────────────────────────────────────────────────────────────
-- 2. INSERT_INVENTARIO  →  33 parámetros según inventarioModel.js
-- ─────────────────────────────────────────────────────────────────────────────


DELIMITER $$
CREATE PROCEDURE INSERT_INVENTARIO(
    -- Categoría
    IN pi_cod_categoria   BIGINT,
    IN pv_nom_categoria   VARCHAR(100),
    IN pv_des_categoria   TEXT,
    IN pv_des_icono       VARCHAR(50),
    -- Almacén
    IN pi_cod_almacen     BIGINT,
    IN pv_nom_almacen     VARCHAR(100),
    IN pv_dir_ubicacion   VARCHAR(200),
    IN pi_cod_empleado    BIGINT,
    IN pi_can_capacidad   INT,
    -- Ítem
    IN pi_cod_item        BIGINT,
    IN pv_nom_item        VARCHAR(150),
    IN pv_des_item        TEXT,
    IN pi_can_total       INT,
    IN pi_can_disponible  INT,
    IN pv_cod_item_unico  VARCHAR(50),
    IN pv_img_foto_url    VARCHAR(255),
    IN pd_fec_adquisicion DATE,
    IN pm_mon_costo       DECIMAL(10,2),
    -- Reserva
    IN pi_cod_reserva     BIGINT,
    IN pi_cod_evento_res  BIGINT,
    IN pi_can_reservada   INT,
    IN pdt_fec_inicio_res DATETIME,
    IN pdt_fec_fin_res    DATETIME,
    IN pv_nom_solicitante VARCHAR(100),
    IN pv_des_notas_res   TEXT,
    -- Asignación
    IN pi_cod_asignacion  BIGINT,
    IN pi_cod_evento_asig BIGINT,
    IN pi_can_asignada    INT,
    IN pdt_fec_salida     DATETIME,
    IN pdt_fec_retorno    DATETIME,
    IN pv_nom_resp_asig   VARCHAR(100),
    IN pv_des_observ      TEXT,
    -- Auditoría
    IN pv_usr_registro    VARCHAR(255)
)
BEGIN
    START TRANSACTION;

    -- Insertar ítem (obligatorio)
    IF pv_nom_item IS NOT NULL THEN
        INSERT INTO IN_INVENTARIO_ITEM
            (NOM_ITEM, DES_ITEM, COD_CATEGORIA, COD_ALMACEN, CAN_TOTAL, CAN_DISPONIBLE,
             COD_ITEM_UNICO, IMG_FOTO_URL, FEC_ADQUISICION, MON_COSTO, USR_REGISTRO, FEC_REGISTRO)
        VALUES
            (pv_nom_item, pv_des_item, pi_cod_categoria, pi_cod_almacen,
             IFNULL(pi_can_total, 0), IFNULL(pi_can_disponible, 0),
             pv_cod_item_unico, pv_img_foto_url, pd_fec_adquisicion, pm_mon_costo,
             IFNULL(pv_usr_registro, 'Sistema'), NOW());

        SET pi_cod_item = LAST_INSERT_ID();
    END IF;

    -- Insertar categoría (si viene nombre de categoría)
    IF pv_nom_categoria IS NOT NULL AND pi_cod_categoria IS NULL THEN
        INSERT INTO IN_CATEGORIAS_INVENTARIO
            (NOM_CATEGORIA, DES_CATEGORIA, DES_ICONO, IND_ACTIVA, USR_REGISTRO, FEC_REGISTRO)
        VALUES
            (pv_nom_categoria, pv_des_categoria, pv_des_icono, TRUE,
             IFNULL(pv_usr_registro, 'Sistema'), NOW());
    END IF;

    -- Insertar almacén (si viene nombre de almacén)
    IF pv_nom_almacen IS NOT NULL AND pi_cod_almacen IS NULL THEN
        INSERT INTO IN_ALMACENES
            (NOM_ALMACEN, DIR_UBICACION, COD_EMPLEADO, CAN_CAPACIDAD, IND_ACTIVO, USR_REGISTRO, FEC_REGISTRO)
        VALUES
            (pv_nom_almacen, pv_dir_ubicacion, pi_cod_empleado, pi_can_capacidad, TRUE,
             IFNULL(pv_usr_registro, 'Sistema'), NOW());
    END IF;

    -- Insertar reserva (si viene evento y cantidad reservada)
    IF pi_cod_evento_res IS NOT NULL AND pi_can_reservada IS NOT NULL AND pi_cod_item IS NOT NULL THEN
        INSERT INTO IN_RESERVAS_INVENTARIO
            (COD_EVENTO, COD_ITEM, CAN_RESERVADA, FEC_INICIO_RESERVA, FEC_FIN_RESERVA,
             IND_ESTADO_RESERVA, NOM_SOLICITANTE, DES_NOTAS, USR_REGISTRO, FEC_REGISTRO)
        VALUES
            (pi_cod_evento_res, pi_cod_item, pi_can_reservada,
             IFNULL(pdt_fec_inicio_res, NOW()), IFNULL(pdt_fec_fin_res, NOW()),
             'ACTIVA', pv_nom_solicitante, pv_des_notas_res,
             IFNULL(pv_usr_registro, 'Sistema'), NOW());

        -- Reducir disponible
        UPDATE IN_INVENTARIO_ITEM
        SET CAN_DISPONIBLE = CAN_DISPONIBLE - pi_can_reservada
        WHERE COD_ITEM = pi_cod_item;
    END IF;

    -- Insertar asignación (si viene evento y cantidad asignada)
    IF pi_cod_evento_asig IS NOT NULL AND pi_can_asignada IS NOT NULL AND pi_cod_item IS NOT NULL THEN
        INSERT INTO IN_ASIGNACION_EVENTO
            (COD_EVENTO, COD_ITEM, CAN_ASIGNADA, FEC_SALIDA, FEC_RETORNO,
             IND_ESTADO, NOM_RESPONSABLE, DES_OBSERVACIONES, USR_REGISTRO, FEC_REGISTRO)
        VALUES
            (pi_cod_evento_asig, pi_cod_item, pi_can_asignada,
             IFNULL(pdt_fec_salida, NOW()), pdt_fec_retorno,
             'PENDIENTE', pv_nom_resp_asig, pv_des_observ,
             IFNULL(pv_usr_registro, 'Sistema'), NOW());

        -- Reducir disponible
        UPDATE IN_INVENTARIO_ITEM
        SET CAN_DISPONIBLE = CAN_DISPONIBLE - pi_can_asignada
        WHERE COD_ITEM = pi_cod_item;
    END IF;

    COMMIT;
END$$
DELIMITER ;

-- ─────────────────────────────────────────────────────────────────────────────
-- 3. SP_IN_UPDATE  →  36 parámetros según inventarioModel.js
-- ─────────────────────────────────────────────────────────────────────────────

DELIMITER $$
CREATE PROCEDURE SP_IN_UPDATE(
    -- Control (acción para soft deletes)
    IN pv_accion          VARCHAR(20),
    -- Auditoría
    IN pv_usr_registro    VARCHAR(255),
    -- Ítem
    IN pi_cod_item        BIGINT,
    IN pv_nom_item        VARCHAR(150),
    IN pv_des_item        TEXT,
    IN pi_can_total       INT,
    IN pi_can_disponible  INT,
    IN pv_ind_estado      ENUM('ACTIVO','BAJA','MANTENIMIENTO'),
    IN pv_cod_item_unico  VARCHAR(50),
    IN pv_img_foto_url    VARCHAR(255),
    IN pd_fec_adquisicion DATE,
    IN pm_mon_costo       DECIMAL(10,2),
    -- Categoría
    IN pi_cod_categoria   BIGINT,
    IN pv_nom_categoria   VARCHAR(100),
    IN pv_des_categoria   TEXT,
    IN pv_des_icono       VARCHAR(50),
    -- Almacén
    IN pi_cod_almacen     BIGINT,
    IN pv_nom_almacen     VARCHAR(100),
    IN pv_dir_ubicacion   VARCHAR(200),
    IN pi_cod_empleado    BIGINT,
    IN pi_can_capacidad   INT,
    -- Reserva
    IN pi_cod_reserva     BIGINT,
    IN pi_can_reservada   INT,
    IN pdt_fec_inicio_res DATETIME,
    IN pdt_fec_fin_res    DATETIME,
    IN pv_ind_estado_res  ENUM('ACTIVA','CANCELADA','COMPLETADA'),
    IN pv_nom_solicitante VARCHAR(100),
    IN pv_des_notas_res   TEXT,
    -- Asignación
    IN pi_cod_asignacion  BIGINT,
    IN pi_can_asignada    INT,
    IN pdt_fec_salida     DATETIME,
    IN pdt_fec_retorno    DATETIME,
    IN pv_ind_estado_asig ENUM('PENDIENTE','ENTREGADO','RETORNADO','PERDIDO'),
    IN pv_ind_condicion   ENUM('BUENO','DANIADO','PERDIDO'),
    IN pv_nom_resp_asig   VARCHAR(100),
    IN pv_des_observ      TEXT
)
BEGIN
    START TRANSACTION;

    -- ── SOFT DELETE ÍTEM ────────────────────────────────────────────────────
    IF pv_accion = 'DEL_IN_ITEM' THEN
        UPDATE IN_INVENTARIO_ITEM
        SET IND_ESTADO   = 'BAJA',
            USR_REGISTRO = IFNULL(pv_usr_registro, USR_REGISTRO),
            FEC_REGISTRO = NOW()
        WHERE COD_ITEM = pi_cod_item;

    -- ── SOFT DELETE CATEGORÍA ───────────────────────────────────────────────
    ELSEIF pv_accion = 'DEL_IN_CATEGORIA' THEN
        UPDATE IN_CATEGORIAS_INVENTARIO
        SET IND_ACTIVA   = FALSE,
            USR_REGISTRO = IFNULL(pv_usr_registro, USR_REGISTRO),
            FEC_REGISTRO = NOW()
        WHERE COD_CATEGORIA = pi_cod_categoria;

    -- ── SOFT DELETE ALMACÉN ─────────────────────────────────────────────────
    ELSEIF pv_accion = 'DEL_IN_ALMACEN' THEN
        UPDATE IN_ALMACENES
        SET IND_ACTIVO   = FALSE,
            USR_REGISTRO = IFNULL(pv_usr_registro, USR_REGISTRO),
            FEC_REGISTRO = NOW()
        WHERE COD_ALMACEN = pi_cod_almacen;

    -- ── UPDATE ÍTEM ─────────────────────────────────────────────────────────
    ELSEIF pi_cod_item IS NOT NULL AND pv_accion IS NULL THEN
        UPDATE IN_INVENTARIO_ITEM
        SET NOM_ITEM        = IFNULL(pv_nom_item,        NOM_ITEM),
            DES_ITEM        = IFNULL(pv_des_item,        DES_ITEM),
            CAN_TOTAL       = IFNULL(pi_can_total,       CAN_TOTAL),
            CAN_DISPONIBLE  = IFNULL(pi_can_disponible,  CAN_DISPONIBLE),
            IND_ESTADO      = IFNULL(pv_ind_estado,      IND_ESTADO),
            COD_ITEM_UNICO  = IFNULL(pv_cod_item_unico,  COD_ITEM_UNICO),
            IMG_FOTO_URL    = IFNULL(pv_img_foto_url,    IMG_FOTO_URL),
            FEC_ADQUISICION = IFNULL(pd_fec_adquisicion, FEC_ADQUISICION),
            MON_COSTO       = IFNULL(pm_mon_costo,       MON_COSTO),
            USR_REGISTRO    = IFNULL(pv_usr_registro,    USR_REGISTRO),
            FEC_REGISTRO    = NOW()
        WHERE COD_ITEM = pi_cod_item;

    -- ── UPDATE CATEGORÍA ────────────────────────────────────────────────────
    ELSEIF pi_cod_categoria IS NOT NULL AND pv_accion IS NULL THEN
        UPDATE IN_CATEGORIAS_INVENTARIO
        SET NOM_CATEGORIA = IFNULL(pv_nom_categoria, NOM_CATEGORIA),
            DES_CATEGORIA = IFNULL(pv_des_categoria, DES_CATEGORIA),
            DES_ICONO     = IFNULL(pv_des_icono,     DES_ICONO),
            USR_REGISTRO  = IFNULL(pv_usr_registro,  USR_REGISTRO),
            FEC_REGISTRO  = NOW()
        WHERE COD_CATEGORIA = pi_cod_categoria;

    -- ── UPDATE ALMACÉN ──────────────────────────────────────────────────────
    ELSEIF pi_cod_almacen IS NOT NULL AND pv_accion IS NULL THEN
        UPDATE IN_ALMACENES
        SET NOM_ALMACEN   = IFNULL(pv_nom_almacen,   NOM_ALMACEN),
            DIR_UBICACION = IFNULL(pv_dir_ubicacion,  DIR_UBICACION),
            COD_EMPLEADO  = IFNULL(pi_cod_empleado,   COD_EMPLEADO),
            CAN_CAPACIDAD = IFNULL(pi_can_capacidad,  CAN_CAPACIDAD),
            USR_REGISTRO  = IFNULL(pv_usr_registro,   USR_REGISTRO),
            FEC_REGISTRO  = NOW()
        WHERE COD_ALMACEN = pi_cod_almacen;

    -- ── UPDATE RESERVA ──────────────────────────────────────────────────────
    ELSEIF pi_cod_reserva IS NOT NULL AND pv_accion IS NULL THEN
        -- Si se cancela, reponer la cantidad disponible del ítem
        IF pv_ind_estado_res = 'CANCELADA' THEN
            UPDATE IN_INVENTARIO_ITEM ii
            JOIN IN_RESERVAS_INVENTARIO r ON ii.COD_ITEM = r.COD_ITEM
            SET ii.CAN_DISPONIBLE = ii.CAN_DISPONIBLE + r.CAN_RESERVADA
            WHERE r.COD_RESERVA = pi_cod_reserva
            AND r.IND_ESTADO_RESERVA <> 'CANCELADA';
        END IF;

        UPDATE IN_RESERVAS_INVENTARIO
        SET CAN_RESERVADA      = IFNULL(pi_can_reservada,   CAN_RESERVADA),
            FEC_INICIO_RESERVA = IFNULL(pdt_fec_inicio_res, FEC_INICIO_RESERVA),
            FEC_FIN_RESERVA    = IFNULL(pdt_fec_fin_res,    FEC_FIN_RESERVA),
            IND_ESTADO_RESERVA = IFNULL(pv_ind_estado_res,  IND_ESTADO_RESERVA),
            NOM_SOLICITANTE    = IFNULL(pv_nom_solicitante,  NOM_SOLICITANTE),
            DES_NOTAS          = IFNULL(pv_des_notas_res,    DES_NOTAS),
            USR_REGISTRO       = IFNULL(pv_usr_registro,     USR_REGISTRO),
            FEC_REGISTRO       = NOW()
        WHERE COD_RESERVA = pi_cod_reserva;

    -- ── UPDATE ASIGNACIÓN ───────────────────────────────────────────────────
    ELSEIF pi_cod_asignacion IS NOT NULL AND pv_accion IS NULL THEN
        -- Si retorna o se pierde, reponer disponible
        IF pv_ind_estado_asig IN ('RETORNADO','PERDIDO') THEN
            UPDATE IN_INVENTARIO_ITEM ii
            JOIN IN_ASIGNACION_EVENTO ae ON ii.COD_ITEM = ae.COD_ITEM
            SET ii.CAN_DISPONIBLE = ii.CAN_DISPONIBLE + ae.CAN_ASIGNADA
            WHERE ae.COD_ASIGNACION = pi_cod_asignacion
            AND ae.IND_ESTADO NOT IN ('RETORNADO','PERDIDO');
        END IF;

        UPDATE IN_ASIGNACION_EVENTO
        SET CAN_ASIGNADA      = IFNULL(pi_can_asignada,    CAN_ASIGNADA),
            FEC_SALIDA        = IFNULL(pdt_fec_salida,     FEC_SALIDA),
            FEC_RETORNO       = IFNULL(pdt_fec_retorno,    FEC_RETORNO),
            IND_ESTADO        = IFNULL(pv_ind_estado_asig, IND_ESTADO),
            IND_CONDICION     = IFNULL(pv_ind_condicion,   IND_CONDICION),
            NOM_RESPONSABLE   = IFNULL(pv_nom_resp_asig,   NOM_RESPONSABLE),
            DES_OBSERVACIONES = IFNULL(pv_des_observ,      DES_OBSERVACIONES),
            USR_REGISTRO      = IFNULL(pv_usr_registro,    USR_REGISTRO),
            FEC_REGISTRO      = NOW()
        WHERE COD_ASIGNACION = pi_cod_asignacion;

    END IF;

    COMMIT;
END$$
DELIMITER ;

-- PROCEDIMIENTOS MODULO DE REPORTES

-- trabajo en el modulo de reportes
-- Carlos David Padilla Velásquez 20221003965  
-- Angie Rebeca Aguirre Rivera 20191007529, modulo Reportes

-- SP_RP_INSERT
-- PROCEDIMIENTO DE INSERT MODULO DE REPORTES
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION

DELIMITER $$
CREATE PROCEDURE SP_RP_INSERT(
    IN  pv_accion              VARCHAR(255)
   -- RP_TABLA_REPORTES
   ,IN  pv_tip_reporte         ENUM('VENTAS','INVENTARIO','FINANCIERO','GENERAL')
   ,IN  pd_fec_emision         DATETIME
   ,IN  pd_fec_periodo_desde   DATE
   ,IN  pd_fec_periodo_hasta   DATE
   ,IN  pv_obs_reporte         TEXT
   ,IN  pv_usr_registro        VARCHAR(255)
   -- RP_GANANCIAS
   ,IN  pi_cod_evento          BIGINT
   ,IN  pd_mon_ingresos        DECIMAL(10,2)
   ,IN  pd_mon_costos          DECIMAL(10,2)
   ,IN  pd_mon_utilidad        DECIMAL(10,2)
   ,IN  pd_fec_cierre          DATE
   -- RP_REPORTE_INVENTARIO
   ,IN  pi_cod_item            BIGINT
   ,IN  pi_can_utilizada       INT
   ,IN  pv_des_estado_final    VARCHAR(50)
   ,IN  pv_obs_notas           TEXT
   -- RP_COSTOS_OPERATIVOS
   ,IN  pi_cod_reporte         BIGINT
   ,IN  pi_cod_proveedor       BIGINT
   ,IN  pv_ind_categoria       ENUM('PERSONAL','LOGISTICA','MARKETING','EQUIPAMIENTO','SERVICIOS','OTROS')
   ,IN  pv_des_costo           VARCHAR(255)
   ,IN  pd_mon_presupuestado   DECIMAL(10,2)
   ,IN  pd_mon_real            DECIMAL(10,2)
   ,IN  pv_obs_costo           TEXT
)
BEGIN
 
    START TRANSACTION;
 
    IF pv_accion = 'INS_RP_TABLA_REPORTES' THEN
 
        INSERT INTO RP_TABLA_REPORTES (
             TIP_REPORTE
            ,FEC_EMISION
            ,FEC_PERIODO_DESDE
            ,FEC_PERIODO_HASTA
            ,OBS_REPORTE
            ,USR_REGISTRO
        ) VALUES (
             pv_tip_reporte
            ,pd_fec_emision
            ,pd_fec_periodo_desde
            ,pd_fec_periodo_hasta
            ,pv_obs_reporte
            ,pv_usr_registro
        );
 
    ELSEIF pv_accion = 'INS_RP_GANANCIAS' THEN
 
        INSERT INTO RP_GANANCIAS (
             COD_EVENTO
            ,MON_INGRESOS
            ,MON_COSTOS
            ,MON_UTILIDAD
            ,FEC_CIERRE
            ,USR_REGISTRO
        ) VALUES (
             pi_cod_evento
            ,pd_mon_ingresos
            ,pd_mon_costos
            ,pd_mon_utilidad
            ,pd_fec_cierre
            ,pv_usr_registro
        );
 
    ELSEIF pv_accion = 'INS_RP_REPORTE_INVENTARIO' THEN
 
        INSERT INTO RP_REPORTE_INVENTARIO (
             COD_ITEM
            ,COD_EVENTO
            ,CAN_UTILIZADA
            ,DES_ESTADO_FINAL
            ,OBS_NOTAS
            ,USR_REGISTRO
        ) VALUES (
             pi_cod_item
            ,pi_cod_evento
            ,pi_can_utilizada
            ,pv_des_estado_final
            ,pv_obs_notas
            ,pv_usr_registro
        );
 
    ELSEIF pv_accion = 'INS_RP_COSTOS_OPERATIVOS' THEN
 
        INSERT INTO RP_COSTOS_OPERATIVOS (
             COD_EVENTO
            ,COD_REPORTE
            ,COD_PROVEEDOR
            ,IND_CATEGORIA
            ,DES_COSTO
            ,MON_PRESUPUESTADO
            ,MON_REAL
            ,OBS_COSTO
            ,USR_REGISTRO
        ) VALUES (
             pi_cod_evento
            ,pi_cod_reporte
            ,pi_cod_proveedor
            ,pv_ind_categoria
            ,pv_des_costo
            ,pd_mon_presupuestado
            ,pd_mon_real
            ,pv_obs_costo
            ,pv_usr_registro
        );
 
    END IF;
 
    COMMIT;
 
END$$
DELIMITER ;

-- SP_RP_UPDATE
-- PROCEDIMIENTO DE UPDATE MODULO DE REPORTES
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION


DELIMITER $$
CREATE PROCEDURE SP_RP_UPDATE(
    IN  pv_accion              VARCHAR(255)
   -- RP_TABLA_REPORTES
   ,IN  pi_cod_reporte         BIGINT
   ,IN  pv_tip_reporte         ENUM('VENTAS','INVENTARIO','FINANCIERO','GENERAL')
   ,IN  pd_fec_emision         DATETIME
   ,IN  pd_fec_periodo_desde   DATE
   ,IN  pd_fec_periodo_hasta   DATE
   ,IN  pv_obs_reporte         TEXT
   -- RP_GANANCIAS
   ,IN  pi_cod_ganancia        BIGINT
   ,IN  pi_cod_evento          BIGINT
   ,IN  pd_mon_ingresos        DECIMAL(10,2)
   ,IN  pd_mon_costos          DECIMAL(10,2)
   ,IN  pd_mon_utilidad        DECIMAL(10,2)
   ,IN  pd_fec_cierre          DATE
   -- RP_REPORTE_INVENTARIO
   ,IN  pi_cod_rep_inventario  BIGINT
   ,IN  pi_cod_item            BIGINT
   ,IN  pi_can_utilizada       INT
   ,IN  pv_des_estado_final    VARCHAR(50)
   ,IN  pv_obs_notas           TEXT
   -- RP_COSTOS_OPERATIVOS
   ,IN  pi_cod_costo           BIGINT
   ,IN  pi_cod_proveedor       BIGINT
   ,IN  pv_ind_categoria       ENUM('PERSONAL','LOGISTICA','MARKETING','EQUIPAMIENTO','SERVICIOS','OTROS')
   ,IN  pv_des_costo           VARCHAR(255)
   ,IN  pd_mon_presupuestado   DECIMAL(10,2)
   ,IN  pd_mon_real            DECIMAL(10,2)
   ,IN  pv_obs_costo           TEXT
)
BEGIN
 
    START TRANSACTION;
 
    IF pv_accion = 'UPD_RP_TABLA_REPORTES' THEN
 
        UPDATE RP_TABLA_REPORTES
        SET
             TIP_REPORTE       = pv_tip_reporte
            ,FEC_EMISION       = pd_fec_emision
            ,FEC_PERIODO_DESDE = pd_fec_periodo_desde
            ,FEC_PERIODO_HASTA = pd_fec_periodo_hasta
            ,OBS_REPORTE       = pv_obs_reporte
        WHERE
            COD_REPORTE = pi_cod_reporte;
 
    ELSEIF pv_accion = 'UPD_RP_GANANCIAS' THEN
 
        UPDATE RP_GANANCIAS
        SET
             COD_EVENTO    = pi_cod_evento
            ,MON_INGRESOS  = pd_mon_ingresos
            ,MON_COSTOS    = pd_mon_costos
            ,MON_UTILIDAD  = pd_mon_utilidad
            ,FEC_CIERRE    = pd_fec_cierre
        WHERE
            COD_GANANCIA = pi_cod_ganancia;
 
    ELSEIF pv_accion = 'UPD_RP_REPORTE_INVENTARIO' THEN
 
        UPDATE RP_REPORTE_INVENTARIO
        SET
             COD_ITEM         = pi_cod_item
            ,COD_EVENTO       = pi_cod_evento
            ,CAN_UTILIZADA    = pi_can_utilizada
            ,DES_ESTADO_FINAL = pv_des_estado_final
            ,OBS_NOTAS        = pv_obs_notas
        WHERE
            COD_REP_INVENTARIO = pi_cod_rep_inventario;
 
    ELSEIF pv_accion = 'UPD_RP_COSTOS_OPERATIVOS' THEN
 
        UPDATE RP_COSTOS_OPERATIVOS
        SET
             COD_EVENTO        = pi_cod_evento
            ,COD_REPORTE       = pi_cod_reporte
            ,COD_PROVEEDOR     = pi_cod_proveedor
            ,IND_CATEGORIA     = pv_ind_categoria
            ,DES_COSTO         = pv_des_costo
            ,MON_PRESUPUESTADO = pd_mon_presupuestado
            ,MON_REAL          = pd_mon_real
            ,OBS_COSTO         = pv_obs_costo
        WHERE
            COD_COSTO = pi_cod_costo;
 
    END IF;
 
    COMMIT;
 
END$$
 DELIMITER ;

-- SP_RP_SELECT
-- PROCEDIMIENTO DE SELECT MODULO DE REPORTES
-- FILTRADO POR IFS ANIDADOS QUE COMPARAN PV ACCION

DELIMITER $$
CREATE PROCEDURE SP_RP_SELECT(
    IN  pv_accion              VARCHAR(255)
   ,IN  pi_cod_reporte         BIGINT
   ,IN  pi_cod_ganancia        BIGINT
   ,IN  pi_cod_rep_inventario  BIGINT
   ,IN  pi_cod_costo           BIGINT
   ,IN  pi_cod_evento          BIGINT
)
BEGIN
 
    START TRANSACTION;
 
    IF pv_accion = 'SEL_RP_TABLA_REPORTES' THEN
 
        SELECT
             COD_REPORTE
            ,TIP_REPORTE
            ,FEC_EMISION
            ,FEC_PERIODO_DESDE
            ,FEC_PERIODO_HASTA
            ,OBS_REPORTE
            ,USR_REGISTRO
            ,FEC_REGISTRO
        FROM
            RP_TABLA_REPORTES
        WHERE
            (pi_cod_reporte IS NULL OR COD_REPORTE = pi_cod_reporte);
 
    ELSEIF pv_accion = 'SEL_RP_GANANCIAS' THEN
 
        SELECT
             COD_GANANCIA
            ,COD_EVENTO
            ,MON_INGRESOS
            ,MON_COSTOS
            ,MON_UTILIDAD
            ,FEC_CIERRE
            ,USR_REGISTRO
            ,FEC_REGISTRO
        FROM
            RP_GANANCIAS
        WHERE
            (pi_cod_ganancia IS NULL OR COD_GANANCIA = pi_cod_ganancia)
        AND (pi_cod_evento   IS NULL OR COD_EVENTO   = pi_cod_evento);
 
    ELSEIF pv_accion = 'SEL_RP_REPORTE_INVENTARIO' THEN
 
        SELECT
             COD_REP_INVENTARIO
            ,COD_ITEM
            ,COD_EVENTO
            ,CAN_UTILIZADA
            ,DES_ESTADO_FINAL
            ,OBS_NOTAS
            ,USR_REGISTRO
            ,FEC_REGISTRO
        FROM
            RP_REPORTE_INVENTARIO
        WHERE
            (pi_cod_rep_inventario IS NULL OR COD_REP_INVENTARIO = pi_cod_rep_inventario)
        AND (pi_cod_evento         IS NULL OR COD_EVENTO         = pi_cod_evento);
 
    ELSEIF pv_accion = 'SEL_RP_COSTOS_OPERATIVOS' THEN
 
        SELECT
             COD_COSTO
            ,COD_EVENTO
            ,COD_REPORTE
            ,COD_PROVEEDOR
            ,IND_CATEGORIA
            ,DES_COSTO
            ,MON_PRESUPUESTADO
            ,MON_REAL
            ,OBS_COSTO
            ,USR_REGISTRO
            ,FEC_REGISTRO
        FROM
            RP_COSTOS_OPERATIVOS
        WHERE
            (pi_cod_costo   IS NULL OR COD_COSTO   = pi_cod_costo)
        AND (pi_cod_reporte IS NULL OR COD_REPORTE = pi_cod_reporte)
        AND (pi_cod_evento  IS NULL OR COD_EVENTO  = pi_cod_evento);
 
    END IF;
 
    COMMIT;
 
END$$
DELIMITER ;




-- PROCEDIMIENTOS PARA LOGIN
-- TODOS LOS INTEGRANTES GRUPO 5

-- 1. SP_AUTH_LOGIN

DELIMITER $$
CREATE PROCEDURE SP_AUTH_LOGIN(
    IN pv_nombre_usr VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
)
BEGIN

    SELECT
         u.COD_USUARIO
        ,u.COD_PERSONA
        ,u.COD_TIPO_USR
        ,u.NOMBRE
        ,u.CLAVE
        ,u.IND_USR
        ,u.IND_PRIMER_ING
        ,p.PRIMER_NOMBRE
        ,p.SEGUNDO_NOMBRE
        ,p.APELLIDO
        ,tu.NOM_TIPO
    FROM USUARIOS u
    INNER JOIN PA_PERSONAS p       ON p.COD_PERSONA  = u.COD_PERSONA
    INNER JOIN PA_TIPO_USUARIOS tu ON tu.COD_TIPO_USR = u.COD_TIPO_USR
    WHERE u.NOMBRE = pv_nombre_usr
    LIMIT 1;

END$$
DELIMITER ;

-- 2. SP_AUTH_VALIDAR_NOMBRE_USR

 
DELIMITER $$
CREATE PROCEDURE SP_AUTH_VALIDAR_NOMBRE_USR(
    IN pv_nombre_usr VARCHAR(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci
)
BEGIN

    SELECT COUNT(*) AS EXISTE
    FROM USUARIOS
    WHERE NOMBRE = pv_nombre_usr;

END$$
DELIMITER ;
 
 

-- 3. SP_AUTH_REGISTRAR_USUARIO

DELIMITER $$
CREATE PROCEDURE SP_AUTH_REGISTRAR_USUARIO(
    IN pi_cod_persona   BIGINT,
    IN pi_cod_tipo_usr  BIGINT,
    IN pv_nombre_usr    VARCHAR(255),
    IN pv_clave         VARCHAR(2000),
    IN pv_token         VARCHAR(6),
    IN pv_usr_ingreso   VARCHAR(255)
)
BEGIN
 
    START TRANSACTION;
 
    INSERT INTO USUARIOS
    (
        COD_PERSONA,
        COD_TIPO_USR,
        NOMBRE,
        CLAVE,
        TOKEN,
        IND_USR,
        IND_PRIMER_ING,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        pi_cod_persona,
        pi_cod_tipo_usr,
        pv_nombre_usr,
        pv_clave,
        IFNULL(pv_token, '000000'),
        '1',
        '1',
        pv_usr_ingreso,
        NOW()
    );
 
    SELECT LAST_INSERT_ID() AS NUEVO_COD_USUARIO;
 
    COMMIT;
 
END$$
DELIMITER ;
 

-- 4. SP_AUTH_CAMBIAR_CLAVE

DELIMITER $$
CREATE PROCEDURE SP_AUTH_CAMBIAR_CLAVE(
    IN pi_cod_usuario  BIGINT,
    IN pv_clave_nueva  VARCHAR(2000),
    IN pv_token_nuevo  VARCHAR(6),
    IN pv_usr_ingreso  VARCHAR(255)
)
BEGIN
 
    START TRANSACTION;
 
    IF pv_token_nuevo IS NOT NULL THEN
        UPDATE USUARIOS
        SET CLAVE          = pv_clave_nueva,
            TOKEN           = pv_token_nuevo,
            IND_PRIMER_ING  = '0',
            USR_INGRESO     = pv_usr_ingreso,
            FEC_INGRESO     = NOW()
        WHERE COD_USUARIO = pi_cod_usuario;
    ELSE
        UPDATE USUARIOS
        SET CLAVE          = pv_clave_nueva,
            IND_PRIMER_ING  = '0',
            USR_INGRESO     = pv_usr_ingreso,
            FEC_INGRESO     = NOW()
        WHERE COD_USUARIO = pi_cod_usuario;
    END IF;
 
    COMMIT;
 
END$$
DELIMITER ;
 

-- 5. SP_AUTH_SELECT_USUARIO_BY_ID

 
DELIMITER $$
CREATE PROCEDURE SP_AUTH_SELECT_USUARIO_BY_ID(
    IN pi_cod_usuario BIGINT
)
BEGIN
 
    SELECT
         u.COD_USUARIO
        ,u.COD_PERSONA
        ,u.COD_TIPO_USR
        ,u.NOMBRE
        ,u.IND_USR
        ,u.IND_PRIMER_ING
        ,p.PRIMER_NOMBRE
        ,p.SEGUNDO_NOMBRE
        ,p.APELLIDO
        ,tu.NOM_TIPO
    FROM USUARIOS u
    INNER JOIN PA_PERSONAS p       ON p.COD_PERSONA  = u.COD_PERSONA
    INNER JOIN PA_TIPO_USUARIOS tu ON tu.COD_TIPO_USR = u.COD_TIPO_USR
    WHERE u.COD_USUARIO = pi_cod_usuario;
 
END$$
DELIMITER ;
 