-- BD NOVAEVENT GRUPO 5
-- MIEMBROS DEL GRUPO

-- JOSUE DAVID ORTIZ ORTIZ 20231003161
-- Jorge Alberto Maradiaga Molina 20152502011
-- Juan Carlos López Avila 20181033368
-- Jaziel Jafeth Funez Andino 20201003788
-- Cindy Michelle Osorto González 20211001885 
-- Joel Fernando Valladares Cruz, 20211024825
-- Carlos David Padilla Velásquez 20221003965 
-- Angie Rebeca Aguirre Rivera 20191007529

-- le volvemos a compartir las tablas lic porque los miembros del modulo de ventas agregaron un campo 
-- a dichas tablas del modulo IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

-- y se cambio en PA_TELEFONOS NUM_AREA de TINYINT A SMALLINT

-- =============================================================================
-- 0. CREAR BASE DE DATOS
-- =============================================================================
CREATE DATABASE IF NOT EXISTS novaevent
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE novaevent;

-- =============================================================================
-- 1. MÓDULO DE PERSONAS (PA)
-- =============================================================================
-- TODOS LOS MIEMBROS DEL GRUPO 5
CREATE TABLE PA_PERSONAS (
   COD_PERSONA    BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DE LA PERSONA'
  ,DNI            VARCHAR(255)  NOT NULL       COMMENT 'IDENTIFICACION DE LA PERSONA'
  ,PRIMER_NOMBRE  VARCHAR(255)  NOT NULL       COMMENT 'PRIMER NOMBRE DE LA PERSONA'
  ,SEGUNDO_NOMBRE VARCHAR(255)                 COMMENT 'SEGUNDO NOMBRE DE LA PERSONA'
  ,APELLIDO       VARCHAR(255)  NOT NULL       COMMENT 'APELLIDO DE LA PERSONA'
  ,SEXO           ENUM('M','F','O','D') NOT NULL COMMENT 'SEXO DE LA PERSONA'
  ,EST_CIVIL      ENUM('S','C','V') NOT NULL   COMMENT 'ESTADO CIVIL DE LA PERSONA'
  ,EDAD           TINYINT       NOT NULL       COMMENT 'EDAD DE LA PERSONA'
  ,TIP_PERSONA    ENUM('N','J') NOT NULL       COMMENT 'NATURAL O JURIDICA'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PAPERSONAS PRIMARY KEY (COD_PERSONA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_TELEFONOS (
   COD_TELEFONO   BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL NUMERO DE TELEFONO'
  ,NUM_AREA       SMALLINT       NOT NULL       COMMENT 'NUMERO DE AREA PARA LLAMAR'
  ,NUM_TELEFONO   INT           NOT NULL       COMMENT 'NUMERO DE TELEFONO'
  ,TIP_TELEFONO   ENUM('C','O','P') NOT NULL   COMMENT 'C:CELULAR O:OFICINA P:PERSONAL'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PATELEFONOS PRIMARY KEY (COD_TELEFONO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE REL_PERSONAS_TELEFONOS (
   COD_REL_PERTEL BIGINT        AUTO_INCREMENT COMMENT 'RELACION PERSONAS Y TELEFONOS'
  ,COD_PERSONA    BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_TELEFONO   BIGINT        NOT NULL       COMMENT 'CODIGO DEL TELEFONO'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_RELPERTEL PRIMARY KEY (COD_REL_PERTEL)
  ,CONSTRAINT FK_RELPERTEL_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_RELPERTEL_TELEFONO FOREIGN KEY (COD_TELEFONO) REFERENCES PA_TELEFONOS(COD_TELEFONO) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_CORREOS (
   COD_CORREO      BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL CORREO ELECTRONICO'
  ,USUARIO_CORREO  VARCHAR(200)                 COMMENT 'USUARIO DE LA DIRECCION DE CORREO'
  ,SERVIDOR_CORREO VARCHAR(200)                 COMMENT 'SERVIDOR DE LA DIRECCION DE CORREO'
  ,TIP_CORREO      ENUM('P','O')                COMMENT 'P:PERSONAL O:OFICINA'
  ,USR_INGRESO     VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO     DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PACORREOS PRIMARY KEY (COD_CORREO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE REL_PERSONAS_CORREOS (
   COD_REL_PERCOR BIGINT        AUTO_INCREMENT COMMENT 'RELACION PERSONAS Y CORREOS'
  ,COD_PERSONA    BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_CORREO     BIGINT        NOT NULL       COMMENT 'CODIGO DEL CORREO'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_RELPERCOR PRIMARY KEY (COD_REL_PERCOR)
  ,CONSTRAINT FK_RELPERCOR_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_RELPERCOR_CORREO FOREIGN KEY (COD_CORREO) REFERENCES PA_CORREOS(COD_CORREO) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_TIPO_USUARIOS (
   COD_TIPO_USR  BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL TIPO DE USUARIO'
  ,NOM_TIPO      VARCHAR(255)  NOT NULL       COMMENT 'NOMBRE DEL TIPO DE USUARIO'
  ,DES_TIPO      VARCHAR(2000) NOT NULL       COMMENT 'DESCRIPCION DEL TIPO DE USUARIO'
  
  ,CONSTRAINT PK_PATIPOUSUARIOS PRIMARY KEY (COD_TIPO_USR)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE USUARIOS (
   COD_USUARIO     BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL USUARIO'
  ,COD_PERSONA     BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_TIPO_USR    BIGINT        NOT NULL       COMMENT 'CODIGO DEL TIPO DE USUARIO'
  ,NOMBRE          VARCHAR(255)  NOT NULL       COMMENT 'NOMBRE DE USUARIO'
  ,CLAVE           VARCHAR(2000) NOT NULL       COMMENT 'CONTRASENA DEL USUARIO'
  ,TOKEN           VARCHAR(6)    NOT NULL       COMMENT 'TOKEN DE ACCESO'
  ,IND_USR         ENUM('1','0') NOT NULL       COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
  ,IND_PRIMER_ING  ENUM('1','0') NOT NULL       COMMENT 'INDICADOR DE PRIMER INGRESO'
  ,USR_INGRESO     VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO     DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_USUARIOS PRIMARY KEY (COD_USUARIO)
  ,CONSTRAINT FK_USUARIO_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_TIPO_USR_USUARIO FOREIGN KEY (COD_TIPO_USR) REFERENCES PA_TIPO_USUARIOS(COD_TIPO_USR) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_TIPO_CLIENTES (
   COD_TIPO_CLI  BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL TIPO DE CLIENTE'
  ,NOM_TIPO_CLI  VARCHAR(255)                 COMMENT 'NOMBRE DEL TIPO DE CLIENTE'
  ,DES_TIPO_CLI  VARCHAR(255)                 COMMENT 'DESCRIPCION DEL TIPO DE CLIENTE'
  ,IND_TIPO_CLI  ENUM('1','0') NOT NULL       COMMENT 'INDICADOR DEL TIPO DE CLIENTE'
  ,USR_INGRESO    VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO    DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PATIPOCLIENTES PRIMARY KEY (COD_TIPO_CLI)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_CLIENTES (
   COD_CLIENTE  BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL CLIENTE'
  ,COD_PERSONA  BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,COD_TIPO_CLI BIGINT        NOT NULL       COMMENT 'CODIGO DEL TIPO DE CLIENTE'
  ,NOM_EMPRESA  VARCHAR(255)                 COMMENT 'EMPRESA A LA QUE PERTENECE EL CLIENTE'
  ,IND_CLIENTE  ENUM('1','0') NOT NULL       COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
  ,USR_INGRESO  VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO  DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PACLIENTES PRIMARY KEY (COD_CLIENTE)
  ,CONSTRAINT FK_CLIENTE_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
  ,CONSTRAINT FK_TIPO_CLI_CLIENTE FOREIGN KEY (COD_TIPO_CLI) REFERENCES PA_TIPO_CLIENTES(COD_TIPO_CLI) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_EMPLEADOS (
   COD_EMPLEADO     BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL EMPLEADO'
  ,COD_PERSONA      BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,CARGO            VARCHAR(100)  NOT NULL       COMMENT 'CARGO DEL EMPLEADO'
  ,FEC_CONTRATACION DATE          NOT NULL       COMMENT 'FECHA DE CONTRATACION'
  ,SALARIO          DECIMAL(10,2) NOT NULL       COMMENT 'SALARIO DEL EMPLEADO'
  ,USR_INGRESO      VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO      DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PAEMPLEADOS PRIMARY KEY (COD_EMPLEADO)
  ,CONSTRAINT FK_EMPLEADO_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE PA_PROVEEDORES (
   COD_PROVEEDOR      BIGINT        AUTO_INCREMENT COMMENT 'CODIGO DEL PROVEEDOR'
  ,COD_PERSONA        BIGINT        NOT NULL       COMMENT 'CODIGO DE LA PERSONA'
  ,EMPRESA            VARCHAR(150)  NOT NULL       COMMENT 'NOMBRE DE LA EMPRESA PROVEEDORA'
  ,CATEGORIA_SERVICIO VARCHAR(100)                 COMMENT 'CATEGORIA DEL SERVICIO QUE PROVEE'
  ,USR_INGRESO        VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO        DATETIME      NOT NULL       COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'
  
  ,CONSTRAINT PK_PAPROVEEDORES PRIMARY KEY (COD_PROVEEDOR)
  ,CONSTRAINT FK_PROVEEDOR_PERSONA FOREIGN KEY (COD_PERSONA) REFERENCES PA_PERSONAS(COD_PERSONA) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;


-- =============================================================================
-- 2. MÓDULO DE RESERVACIÓN (RE)
-- =============================================================================
-- JOSUE DAVID ORTIZ ORTIZ 20231003161
-- Jorge Alberto Maradiaga Molina 20152502011

CREATE TABLE RE_ESPACIO (
   COD_ESPACIO      INT           AUTO_INCREMENT COMMENT 'Codigo unico del espacio'
  ,NOM_ESPACIO      VARCHAR(100)  NOT NULL       COMMENT 'Nombre descriptivo del espacio'
  ,CAN_CAPACIDAD    INT           NOT NULL       COMMENT 'Capacidad maxima de personas'
  ,TIP_ESPACIO      ENUM('SALON','AUDITORIO','AREA_EXTERIOR','SALA_REUNION') NOT NULL COMMENT 'Tipo de espacio configurado'
  ,IND_ESTADO       ENUM('DISPONIBLE','MANTENIMIENTO','INACTIVO') NOT NULL DEFAULT 'DISPONIBLE' COMMENT 'Estado operativo del espacio'
  ,MON_PRECIO_HORA  DECIMAL(10,2) NOT NULL       COMMENT 'Precio de alquiler por hora'
  
  ,CONSTRAINT PK_REESPACIOO PRIMARY KEY (COD_ESPACIO)
  ,CONSTRAINT CK_RE_REESPACIOO_TIPESPAC CHECK (TIP_ESPACIO IN ('SALON', 'AUDITORIO', 'AREA_EXTERIOR', 'SALA_REUNION'))
  ,CONSTRAINT CK_RE_REESPACIOO_INDESTAD CHECK (IND_ESTADO IN ('DISPONIBLE', 'MANTENIMIENTO', 'INACTIVO'))
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RE_RESERVACION (
   COD_RESERVACION  INT           AUTO_INCREMENT COMMENT 'Codigo de la reservacion'
  ,COD_ESPACIO      INT           NOT NULL       COMMENT 'Codigo del espacio reservado'
  ,COD_CLIENTE      BIGINT        NOT NULL       COMMENT 'Codigo del cliente que reserva'
  ,COD_EMPLEADO     BIGINT        NOT NULL       COMMENT 'Codigo del empleado que gestiona'
  ,FEC_INICIO       DATETIME      NOT NULL       COMMENT 'Fecha y hora de inicio de la reservacion'
  ,FEC_FIN          DATETIME      NOT NULL       COMMENT 'Fecha y hora de fin de la reservacion'
  ,IND_ESTADO       ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA') NOT NULL DEFAULT 'PENDIENTE' COMMENT 'Estado actual de la reservacion'
  ,DES_NOTAS        TEXT                         COMMENT 'Notas adicionales de la reservacion'
  ,USR_INGRESO      VARCHAR(255)  NOT NULL       COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha en que se ingreso el registro'
  
  ,CONSTRAINT PK_RERESERVACI PRIMARY KEY (COD_RESERVACION)
  ,CONSTRAINT FK_RERESERVACI_REESPACIO FOREIGN KEY (COD_ESPACIO) REFERENCES RE_ESPACIO(COD_ESPACIO)
  ,CONSTRAINT FK_RERESERVACI_PACLIENTES FOREIGN KEY (COD_CLIENTE) REFERENCES PA_CLIENTES(COD_CLIENTE) ON DELETE CASCADE
  ,CONSTRAINT FK_RERESERVACI_PAEMPLEADOS FOREIGN KEY (COD_EMPLEADO) REFERENCES PA_EMPLEADOS(COD_EMPLEADO) ON DELETE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RE_ESPACIO_OCUPADO (
   COD_ESPA_OCUP    INT           AUTO_INCREMENT COMMENT 'Codigo del bloqueo de espacio'
  ,COD_ESPACIO      INT           NOT NULL       COMMENT 'Codigo del espacio bloqueado'
  ,FEC_INICIO       DATETIME      NOT NULL       COMMENT 'Fecha de inicio del bloqueo'
  ,FEC_FIN          DATETIME      NOT NULL       COMMENT 'Fecha de fin del bloqueo'
  ,DES_MOTIVO       VARCHAR(200)                 COMMENT 'Descripcion del motivo del bloqueo'
  ,USR_INGRESO      VARCHAR(255)  NOT NULL       COMMENT 'Usuario que ingreso el registro'
  ,FEC_INGRESO      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha en que se ingreso el registro'
  
  ,CONSTRAINT PK_REESPACOCUP PRIMARY KEY (COD_ESPA_OCUP)
  ,CONSTRAINT FK_REESPACOCUP_REESPACIO FOREIGN KEY (COD_ESPACIO) REFERENCES RE_ESPACIO(COD_ESPACIO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RE_HISTORIAL_RESERVACION (
   CSC_HISTORIAL    INT           AUTO_INCREMENT COMMENT 'Consecutivo del historial'
  ,COD_RESERVACION  INT           NOT NULL       COMMENT 'Codigo de la reservacion asociada'
  ,IND_ESTADO_ANT    ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA') NOT NULL COMMENT 'Estado previo del registro'
  ,IND_ESTADO_NUE    ENUM('PENDIENTE','CONFIRMADA','CANCELADA','COMPLETADA') NOT NULL COMMENT 'Estado nuevo asignado'
  ,COD_PERSONA_CAM  BIGINT        NOT NULL       COMMENT 'Codigo del usuario que cambio el estado'
  ,FEC_ADICION      DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'Fecha y hora del cambio de estado'
  
  ,CONSTRAINT PK_REHISTRESER PRIMARY KEY (CSC_HISTORIAL)
  ,CONSTRAINT FK_REHISTRESER_RERESERVACI FOREIGN KEY (COD_RESERVACION) REFERENCES RE_RESERVACION(COD_RESERVACION) ON DELETE CASCADE
  ,CONSTRAINT FK_REHISTRESER_PAPERSONAS FOREIGN KEY (COD_PERSONA_CAM) REFERENCES PA_PERSONAS(COD_PERSONA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;


-- =============================================================================
-- 3. MÓDULO DE VENTAS (VE)
-- =============================================================================

-- Juan Carlos López Avila 20181033368
-- Jaziel Jafeth Funez Andino 20201003788
-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
CREATE TABLE VE_CATEGORIA_EVENTOS (
   COD_CATEGORIA BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA CATEGORIA'
  ,NOM_CATEGORIA VARCHAR(100) NOT NULL COMMENT 'NOMBRE DE LA CATEGORIA'
  ,DES_CATEGORIA TEXT COMMENT 'DESCRIPCION DE LA CATEGORIA'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
 
  ,CONSTRAINT PK_VECATEGORIAEVENTOS PRIMARY KEY (COD_CATEGORIA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_CICLO_EVENTO (
   COD_CICLO_EVENTO INT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL CICLO'
  ,NOM_CICLO VARCHAR(100) NOT NULL COMMENT 'NOMBRE DEL CICLO (ej: ANUAL, MENSUAL, UNICO)'
  ,DES_CICLO VARCHAR(255) COMMENT 'DESCRIPCION DEL CICLO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'
  ,USR_INGRESO VARCHAR(255) NOT NULL COMMENT 'USUARIO QUE INGRESO EL REGISTRO'
  ,FEC_INGRESO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA EN QUE SE INGRESO EL REGISTRO'

  ,CONSTRAINT PK_VECICLOEVEN PRIMARY KEY (COD_CICLO_EVENTO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_EVENTOS (
   COD_EVENTO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL EVENTO'
  ,COD_CATEGORIA BIGINT NOT NULL COMMENT 'LLAVE FORANEA DE LA CATEGORIA'
  ,COD_CICLO_EVENTO INT NOT NULL COMMENT 'LLAVE FORANEA DEL CICLO DEL EVENTO'
  ,COD_RESERVACION INT COMMENT 'LLAVE FORANEA DE LA RESERVACION DEL ESPACIO (NULLABLE)'
  ,NOM_EVENTO VARCHAR(150) NOT NULL COMMENT 'NOMBRE DEL EVENTO'
  ,DES_EVENTO TEXT COMMENT 'DESCRIPCION DEL EVENTO'
  ,FEC_EVENTO DATE NOT NULL COMMENT 'FECHA DEL EVENTO'
  ,HOR_EVENTO TIME NOT NULL COMMENT 'HORA DEL EVENTO'
  ,DES_LUGAR VARCHAR(150) NOT NULL COMMENT 'LUGAR DEL EVENTO (referencia textual de respaldo)'
  ,NUM_CAPACIDAD INT NOT NULL COMMENT 'CAPACIDAD MAXIMA DEL EVENTO'
  ,IND_ESTADO ENUM('ACTIVO','CANCELADO','FINALIZADO') NOT NULL COMMENT 'ESTADO DEL EVENTO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEEVENTOS PRIMARY KEY (COD_EVENTO)
  ,CONSTRAINT FK_VEEVENTOS_CATEGORIA FOREIGN KEY (COD_CATEGORIA) REFERENCES VE_CATEGORIA_EVENTOS(COD_CATEGORIA)
  ,CONSTRAINT FK_VEEVENTOS_CICLO FOREIGN KEY (COD_CICLO_EVENTO) REFERENCES VE_CICLO_EVENTO(COD_CICLO_EVENTO)
  ,CONSTRAINT FK_VEEVENTOS_RESERVACION FOREIGN KEY (COD_RESERVACION) REFERENCES RE_RESERVACION(COD_RESERVACION) ON DELETE SET NULL
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_BOLETOS (
   COD_BOLETO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL BOLETO'
  ,COD_EVENTO BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,TIP_BOLETO ENUM('VIP','GENERAL','PREFERENCIAL','BACKSTAGE') NOT NULL COMMENT 'TIPO DE BOLETO'
  ,MON_PRECIO DECIMAL(10,2) NOT NULL COMMENT 'PRECIO DEL BOLETO'
  ,NUM_DISPONIBLE INT NOT NULL COMMENT 'CANTIDAD DISPONIBLE'
  ,DES_BOLETO TEXT COMMENT 'DESCRIPCION DEL BOLETO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEBOLETOS PRIMARY KEY (COD_BOLETO)
  ,CONSTRAINT FK_VEBOLETOS_EVENTOS FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_VENTAS (
   COD_VENTA BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA VENTA'
  ,COD_CLIENTE BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL CLIENTE (PA_CLIENTES)'
  ,FEC_VENTA DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DE LA VENTA'
  ,MON_TOTAL DECIMAL(10,2) NOT NULL COMMENT 'TOTAL DE LA VENTA'
  ,IND_METODO_PAGO ENUM('EFECTIVO','TARJETA','TRANSFERENCIA') NOT NULL COMMENT 'METODO DE PAGO'
  ,IND_ESTADO_VENTA ENUM('PAGADA','PENDIENTE','CANCELADA') NOT NULL COMMENT 'ESTADO DE LA VENTA'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEVENTAS PRIMARY KEY (COD_VENTA)
  ,CONSTRAINT FK_VEVENTAS_PACLIENTES FOREIGN KEY (COD_CLIENTE) REFERENCES PA_CLIENTES(COD_CLIENTE)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_DETALLE_VENTAS (
   COD_DETALLE BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL DETALLE'
  ,COD_VENTA BIGINT NOT NULL COMMENT 'LLAVE FORANEA DE LA VENTA'
  ,COD_BOLETO BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL BOLETO'
  ,NUM_CANTIDAD INT NOT NULL COMMENT 'CANTIDAD DE BOLETOS'
  ,MON_PRECIO_UNIT DECIMAL(10,2) NOT NULL COMMENT 'PRECIO UNITARIO'
  ,MON_SUBTOTAL DECIMAL(10,2) NOT NULL COMMENT 'SUBTOTAL'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEDETALLEVENTAS PRIMARY KEY (COD_DETALLE)
  ,CONSTRAINT FK_VEDETVENT_VENTA FOREIGN KEY (COD_VENTA) REFERENCES VE_VENTAS(COD_VENTA)
  ,CONSTRAINT FK_VEDETVENT_BOLETO FOREIGN KEY (COD_BOLETO) REFERENCES VE_BOLETOS(COD_BOLETO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- campo agregado
-- IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

CREATE TABLE VE_PAGOS (
   COD_PAGO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL PAGO'
  ,COD_VENTA BIGINT NOT NULL COMMENT 'LLAVE FORANEA DE LA VENTA'
  ,MON_PAGO DECIMAL(10,2) NOT NULL COMMENT 'MONTO DEL PAGO'
  ,FEC_PAGO DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT 'FECHA DEL PAGO'
  ,COD_REFERENCIA VARCHAR(100) COMMENT 'REFERENCIA DEL PAGO'
  ,IND_ESTADO_PAGO ENUM('APROBADO','PENDIENTE','RECHAZADO') NOT NULL COMMENT 'ESTADO DEL PAGO'
  ,IND_ACTIVO ENUM('1','0') NOT NULL DEFAULT '1' COMMENT 'INDICADOR 0=INACTIVO 1=ACTIVO'

  ,CONSTRAINT PK_VEPAGOS PRIMARY KEY (COD_PAGO)
  ,CONSTRAINT FK_VEPAGOS_VENTAS FOREIGN KEY (COD_VENTA) REFERENCES VE_VENTAS(COD_VENTA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

-- =============================================================================
-- 4. MÓDULO DE INVENTARIO (IN)
-- =============================================================================

-- Cindy Michelle Osorto González 20211001885 
-- Joel Fernando Valladares Cruz, 20211024825

CREATE TABLE IN_CATEGORIAS_INVENTARIO (
   COD_CATEGORIA BIGINT        AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA CATEGORIA'
  ,NOM_CATEGORIA VARCHAR(100)  NOT NULL COMMENT 'NOMBRE DE LA CATEGORIA'
  ,DES_CATEGORIA TEXT                   COMMENT 'DESCRIPCION DE LA CATEGORIA'
  ,DES_ICONO     VARCHAR(50)            COMMENT 'ICONO REPRESENTATIVO DE LA CATEGORIA'
  ,IND_ACTIVA    BOOLEAN       NOT NULL DEFAULT TRUE COMMENT 'INDICA SI LA CATEGORIA ESTA ACTIVA'
  ,USR_REGISTRO  VARCHAR(255)  NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO  DATETIME      NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INCATEINVE PRIMARY KEY (COD_CATEGORIA)
  ,CONSTRAINT UK_INCATEINVE_NOMCATEG UNIQUE (NOM_CATEGORIA)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_ALMACENES (
   COD_ALMACEN     BIGINT        AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL ALMACEN'
  ,NOM_ALMACEN     VARCHAR(100)  NOT NULL COMMENT 'NOMBRE DEL ALMACEN'
  ,DIR_UBICACION   VARCHAR(200)           COMMENT 'UBICACION FISICA DEL ALMACEN'
  ,COD_EMPLEADO    BIGINT                 COMMENT 'LLAVE FORANEA DEL EMPLEADO RESPONSABLE DEL ALMACEN'
  ,CAN_CAPACIDAD   INT                    COMMENT 'CAPACIDAD MAXIMA DE ITEMS'
  ,IND_ACTIVO      BOOLEAN       NOT NULL DEFAULT TRUE COMMENT 'INDICA SI EL ALMACEN ESTA ACTIVO'
  ,USR_REGISTRO    VARCHAR(255)  NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO    DATETIME      NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INALMACENE PRIMARY KEY (COD_ALMACEN)
  ,CONSTRAINT FK_INALMACENE_EMPLEADO FOREIGN KEY (COD_EMPLEADO) REFERENCES PA_EMPLEADOS(COD_EMPLEADO) ON DELETE SET NULL
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_INVENTARIO_ITEM (
   COD_ITEM        BIGINT        AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL ITEM'
  ,NOM_ITEM        VARCHAR(150)  NOT NULL COMMENT 'NOMBRE DEL ITEM'
  ,DES_ITEM        TEXT                   COMMENT 'DESCRIPCION DETALLADA DEL ITEM'
  ,COD_CATEGORIA   BIGINT                 COMMENT 'LLAVE FORANEA DE CATEGORIA'
  ,COD_ALMACEN     BIGINT                 COMMENT 'LLAVE FORANEA DEL ALMACEN'
  ,CAN_TOTAL       INT           NOT NULL DEFAULT 0 COMMENT 'CANTIDAD TOTAL DEL ITEM'
  ,CAN_DISPONIBLE  INT           NOT NULL DEFAULT 0 COMMENT 'CANTIDAD DISPONIBLE DEL ITEM'
  ,IND_ESTADO      ENUM('ACTIVO','BAJA','MANTENIMIENTO') NOT NULL DEFAULT 'ACTIVO' COMMENT 'ESTADO ACTUAL DEL ITEM'
  ,COD_ITEM_UNICO  VARCHAR(50)            COMMENT 'CODIGO UNICO DEL ITEM'
  ,IMG_FOTO_URL    VARCHAR(255)           COMMENT 'URL DE LA FOTO DEL ITEM'
  ,FEC_ADQUISICION DATE                   COMMENT 'FECHA EN QUE SE ADQUIRIO EL ITEM'
  ,MON_COSTO       DECIMAL(10,2)          COMMENT 'COSTO UNITARIO DEL ITEM'
  ,USR_REGISTRO    VARCHAR(255)  NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO    DATETIME      NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_ININVEITEM PRIMARY KEY (COD_ITEM)
  ,CONSTRAINT UK_ININVEITEM_ITEMUNIQUE UNIQUE (COD_ITEM_UNICO)
  ,CONSTRAINT FK_ININVEITEM_INCATEINVE FOREIGN KEY (COD_CATEGORIA) REFERENCES IN_CATEGORIAS_INVENTARIO(COD_CATEGORIA) ON DELETE SET NULL ON UPDATE CASCADE
  ,CONSTRAINT FK_ININVEITEM_INALMACENE FOREIGN KEY (COD_ALMACEN) REFERENCES IN_ALMACENES(COD_ALMACEN) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_RESERVAS_INVENTARIO (
   COD_RESERVA          BIGINT       AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA RESERVA'
  ,COD_EVENTO          BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,COD_ITEM            BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL ITEM'
  ,CAN_RESERVADA       INT          NOT NULL COMMENT 'CANTIDAD DE ITEMS RESERVADOS'
  ,FEC_INICIO_RESERVA  DATETIME     NOT NULL COMMENT 'FECHA DE INICIO DE LA RESERVA'
  ,FEC_FIN_RESERVA     DATETIME     NOT NULL COMMENT 'FECHA DE FIN DE LA RESERVA'
  ,IND_ESTADO_RESERVA  ENUM('ACTIVA','CANCELADA','COMPLETADA') NOT NULL DEFAULT 'ACTIVA' COMMENT 'ESTADO DE LA RESERVA'
  ,NOM_SOLICITANTE     VARCHAR(100)          COMMENT 'PERSONA QUE SOLICITA LA RESERVA'
  ,DES_NOTAS           TEXT                   COMMENT 'NOTAS ADICIONALES DE LA RESERVA'
  ,USR_REGISTRO        VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO        DATETIME     NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INRESINVEN PRIMARY KEY (COD_RESERVA)
  ,CONSTRAINT FK_INRESINVEN_ININVEITEM FOREIGN KEY (COD_ITEM) REFERENCES IN_INVENTARIO_ITEM(COD_ITEM) ON DELETE RESTRICT ON UPDATE CASCADE
  ,CONSTRAINT FK_INRESINVEN_EVENTOS FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE IN_ASIGNACION_EVENTO (
   COD_ASIGNACION    BIGINT       AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA ASIGNACION'
  ,COD_EVENTO        BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,COD_ITEM          BIGINT       NOT NULL COMMENT 'LLAVE FORANEA DEL ITEM'
  ,CAN_ASIGNADA      INT          NOT NULL COMMENT 'CANTIDAD DE ITEMS ASIGNADOS AL EVENTO'
  ,FEC_SALIDA        DATETIME     NOT NULL COMMENT 'FECHA DE SALIDA DEL ITEM'
  ,FEC_RETORNO       DATETIME              COMMENT 'FECHA DE RETORNO DEL ITEM'
  ,IND_ESTADO        ENUM('PENDIENTE','ENTREGADO','RETORNADO','PERDIDO') NOT NULL DEFAULT 'PENDIENTE' COMMENT 'ESTADO DE LA ASIGNACION'
  ,IND_CONDICION     ENUM('BUENO','DANIADO','PERDIDO') COMMENT 'CONDICION DEL ITEM AL RETORNAR'
  ,NOM_RESPONSABLE   VARCHAR(100)          COMMENT 'RESPONSABLE DE LA ASIGNACION'
  ,DES_OBSERVACIONES TEXT                   COMMENT 'OBSERVACIONES DE LA ASIGNACION'
  ,USR_REGISTRO      VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO      DATETIME     NOT NULL DEFAULT NOW() COMMENT 'FECHA QUE SE REGISTRA'
  
  ,CONSTRAINT PK_INASIGEVEN PRIMARY KEY (COD_ASIGNACION)
  ,CONSTRAINT FK_INASIGEVEN_ININVEITEM FOREIGN KEY (COD_ITEM) REFERENCES IN_INVENTARIO_ITEM(COD_ITEM) ON DELETE RESTRICT ON UPDATE CASCADE
  ,CONSTRAINT FK_INASIGEVEN_EVENTOS FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO) ON DELETE RESTRICT ON UPDATE CASCADE
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;


-- =============================================================================
-- 5. MÓDULO DE REPORTES (RP)
-- =============================================================================

-- Carlos David Padilla Velásquez 20221003965 
-- Angie Rebeca Aguirre Rivera 20191007529

CREATE TABLE RP_TABLA_REPORTES (
   COD_REPORTE        BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL REPORTE'
  ,TIP_REPORTE        ENUM('VENTAS','INVENTARIO','FINANCIERO','GENERAL') NOT NULL COMMENT 'TIPO DE REPORTE'
  ,FEC_EMISION        DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE EMISION'
  ,FEC_PERIODO_DESDE DATE                   COMMENT 'FECHA INICIAL DEL PERIODO'
  ,FEC_PERIODO_HASTA DATE                   COMMENT 'FECHA FINAL DEL PERIODO'
  ,OBS_REPORTE        TEXT                  COMMENT 'OBSERVACIONES DEL REPORTE'
  ,USR_REGISTRO      VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO      DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPTABLREPO PRIMARY KEY (COD_REPORTE)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RP_GANANCIAS (
   COD_GANANCIA  BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DE LA GANANCIA'
  ,COD_EVENTO    BIGINT NOT NULL    COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,MON_INGRESOS  DECIMAL(10,2)      COMMENT 'TOTAL DE INGRESOS'
  ,MON_COSTOS    DECIMAL(10,2)      COMMENT 'TOTAL DE COSTOS'
  ,MON_UTILIDAD  DECIMAL(10,2)      COMMENT 'UTILIDAD NETA'
  ,FEC_CIERRE    DATE               COMMENT 'FECHA DE CIERRE'
  ,USR_REGISTRO  VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO  DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPGANANCIA PRIMARY KEY (COD_GANANCIA)
  ,CONSTRAINT FK_RPGANANCIA_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RP_REPORTE_INVENTARIO (
   COD_REP_INVENTARIO BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL REPORTE'
  ,COD_ITEM            BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL ITEM'
  ,COD_EVENTO          BIGINT NOT NULL COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,CAN_UTILIZADA       INT                 COMMENT 'CANTIDAD UTILIZADA'
  ,DES_ESTADO_FINAL    VARCHAR(50)         COMMENT 'ESTADO FINAL DEL ITEM'
  ,OBS_NOTAS           TEXT                COMMENT 'NOTAS ADICIONALES'
  ,USR_REGISTRO        VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO        DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPREPINVEN PRIMARY KEY (COD_REP_INVENTARIO)
  ,CONSTRAINT FK_RREPINVEN_EVENTO FOREIGN KEY (COD_EVENTO) REFERENCES VE_EVENTOS(COD_EVENTO)
  ,CONSTRAINT FK_RREPINVEN_ITEM   FOREIGN KEY (COD_ITEM)   REFERENCES IN_INVENTARIO_ITEM(COD_ITEM)
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;

CREATE TABLE RP_COSTOS_OPERATIVOS (
   COD_COSTO          BIGINT AUTO_INCREMENT COMMENT 'LLAVE PRIMARIA DEL COSTO'
  ,COD_EVENTO         BIGINT NOT NULL   COMMENT 'LLAVE FORANEA DEL EVENTO'
  ,COD_REPORTE        BIGINT            COMMENT 'LLAVE FORANEA DEL REPORTE'
  ,COD_PROVEEDOR      BIGINT            COMMENT 'LLAVE FORANEA DEL PROVEEDOR (PA_PROVEEDORES)'
  ,IND_CATEGORIA      ENUM('PERSONAL','LOGISTICA','MARKETING','EQUIPAMIENTO','SERVICIOS','OTROS') NOT NULL COMMENT 'CATEGORIA DEL COSTO'
  ,DES_COSTO          VARCHAR(255)      COMMENT 'DESCRIPCION DEL COSTO'
  ,MON_PRESUPUESTADO  DECIMAL(10,2) NOT NULL COMMENT 'MONTO PRESUPUESTADO'
  ,MON_REAL           DECIMAL(10,2) NOT NULL COMMENT 'MONTO REAL'
  ,OBS_COSTO          TEXT              COMMENT 'OBSERVACIONES'
  ,USR_REGISTRO       VARCHAR(255) NOT NULL DEFAULT 'Sistema' COMMENT 'USUARIO QUE REGISTRA'
  ,FEC_REGISTRO       DATETIME NOT NULL DEFAULT NOW() COMMENT 'FECHA DE REGISTRO'
  
  ,CONSTRAINT PK_RPCOSTOPER PRIMARY KEY (COD_COSTO)
  ,CONSTRAINT FK_RPCOSTOPER_EVENTO     FOREIGN KEY (COD_EVENTO)     REFERENCES VE_EVENTOS(COD_EVENTO)
  ,CONSTRAINT FK_RPCOSTOPER_REPORTE    FOREIGN KEY (COD_REPORTE)    REFERENCES RP_TABLA_REPORTES(COD_REPORTE)
  ,CONSTRAINT FK_RPCOSTOPER_PROVEEDOR  FOREIGN KEY (COD_PROVEEDOR) REFERENCES PA_PROVEEDORES(COD_PROVEEDOR) ON DELETE SET NULL
) ENGINE=INNODB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;



-- =============================================================================
-- PROCEDIMIENTOS ALMACENADOS - MÓDULO DE PERSONAS
-- =============================================================================

-- PROCEDIMIENTO PARA INSERTAR A LAS TABLAS DEL MODULO PERSONAS 
-- FILTRADO POR MEDIO DE IFS ANIDADOS

DELIMITER $$
CREATE PROCEDURE SP_INSERT_PERSONAS(
    IN PV_ACCION VARCHAR(50),

    -- PERSONAS
    IN PV_DNI VARCHAR(255),
    IN PV_PRIMER_NOMBRE VARCHAR(255),
    IN PV_SEGUNDO_NOMBRE VARCHAR(255),
    IN PV_APELLIDO VARCHAR(255),
    IN PV_SEXO ENUM('M','F','O','D'),
    IN PV_EST_CIVIL ENUM('S','C','V'),
    IN PI_EDAD TINYINT,
    IN PV_TIP_PERSONA ENUM('N','J'),

    -- TELEFONOS
    IN PI_NUM_AREA SMALLINT,
    IN PI_NUM_TELEFONO INT,
    IN PV_TIP_TELEFONO ENUM('C','O','P'),

    -- CORREOS
    IN PV_USUARIO_CORREO VARCHAR(200),
    IN PV_SERVIDOR_CORREO VARCHAR(200),
    IN PV_TIP_CORREO ENUM('P','O'),

    -- TIPO USUARIO
    IN PV_NOM_TIPO VARCHAR(255),
    IN PV_DES_TIPO VARCHAR(2000),

    -- USUARIOS
    IN PI_COD_PERSONA BIGINT,
    IN PI_COD_TIPO_USR BIGINT,
    IN PV_NOMBRE VARCHAR(255),
    IN PV_CLAVE VARCHAR(2000),
    IN PV_TOKEN VARCHAR(6),
    IN PV_IND_USR ENUM('1','0'),
    IN PV_IND_PRIMER_ING ENUM('1','0'),

    -- TIPO CLIENTE
    IN PV_NOM_TIPO_CLI VARCHAR(255),
    IN PV_DES_TIPO_CLI VARCHAR(255),
    IN PV_IND_TIPO_CLI ENUM('1','0'),

    -- CLIENTES
    IN PI_COD_TIPO_CLI BIGINT,
    IN PV_NOM_EMPRESA VARCHAR(255),
    IN PV_IND_CLIENTE ENUM('1','0'),

    -- EMPLEADOS
    IN PV_CARGO VARCHAR(100),
    IN PD_FEC_CONTRATACION DATE,
    IN PM_SALARIO DECIMAL(10,2),

    -- PROVEEDORES
    IN PV_EMPRESA_PROV VARCHAR(150),
    IN PV_CATEGORIA_SERVICIO VARCHAR(100),

    -- AUDITORIA
    IN PV_USR_INGRESO VARCHAR(255)

)
BEGIN
START TRANSACTION;

IF PV_ACCION='INS_PERSONA' THEN
    INSERT INTO PA_PERSONAS
    (
        DNI,
        PRIMER_NOMBRE,
        SEGUNDO_NOMBRE,
        APELLIDO,
        SEXO,
        EST_CIVIL,
        EDAD,
        TIP_PERSONA,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PV_DNI,
        PV_PRIMER_NOMBRE,
        PV_SEGUNDO_NOMBRE,
        PV_APELLIDO,
        PV_SEXO,
        PV_EST_CIVIL,
        PI_EDAD,
        PV_TIP_PERSONA,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_TELEFONO' THEN
    INSERT INTO PA_TELEFONOS
    (
        NUM_AREA,
        NUM_TELEFONO,
        TIP_TELEFONO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_NUM_AREA,
        PI_NUM_TELEFONO,
        PV_TIP_TELEFONO,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_REL_PERSONA_TELEFONO' THEN
    INSERT INTO REL_PERSONAS_TELEFONOS
    (
        COD_PERSONA,
        COD_TELEFONO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_USR,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_CORREO' THEN
    INSERT INTO PA_CORREOS
    (
        USUARIO_CORREO,
        SERVIDOR_CORREO,
        TIP_CORREO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PV_USUARIO_CORREO,
        PV_SERVIDOR_CORREO,
        PV_TIP_CORREO,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_REL_PERSONA_CORREO' THEN
    INSERT INTO REL_PERSONAS_CORREOS
    (
        COD_PERSONA,
        COD_CORREO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_USR,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_TIPO_USUARIO' THEN
    INSERT INTO PA_TIPO_USUARIOS
    (
        NOM_TIPO,
        DES_TIPO
    )
    VALUES
    (
        PV_NOM_TIPO,
        PV_DES_TIPO
    );

ELSEIF PV_ACCION='INS_USUARIO' THEN
    INSERT INTO USUARIOS
    (
        COD_PERSONA,
        COD_TIPO_USR,
        NOMBRE,
        CLAVE,
        TOKEN,
        IND_USR,
        IND_PRIMER_ING,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_USR,
        PV_NOMBRE,
        PV_CLAVE,
        PV_TOKEN,
        PV_IND_USR,
        PV_IND_PRIMER_ING,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_TIPO_CLIENTE' THEN
    INSERT INTO PA_TIPO_CLIENTES
    (
        NOM_TIPO_CLI,
        DES_TIPO_CLI,
        IND_TIPO_CLI,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PV_NOM_TIPO_CLI,
        PV_DES_TIPO_CLI,
        PV_IND_TIPO_CLI,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_CLIENTE' THEN
    INSERT INTO PA_CLIENTES
    (
        COD_PERSONA,
        COD_TIPO_CLI,
        NOM_EMPRESA,
        IND_CLIENTE,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PI_COD_TIPO_CLI,
        PV_NOM_EMPRESA,
        PV_IND_CLIENTE,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_EMPLEADO' THEN
    INSERT INTO PA_EMPLEADOS
    (
        COD_PERSONA,
        CARGO,
        FEC_CONTRATACION,
        SALARIO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PV_CARGO,
        PD_FEC_CONTRATACION,
        PM_SALARIO,
        PV_USR_INGRESO,
        NOW()
    );

ELSEIF PV_ACCION='INS_PROVEEDOR' THEN
    INSERT INTO PA_PROVEEDORES
    (
        COD_PERSONA,
        EMPRESA,
        CATEGORIA_SERVICIO,
        USR_INGRESO,
        FEC_INGRESO
    )
    VALUES
    (
        PI_COD_PERSONA,
        PV_EMPRESA_PROV,
        PV_CATEGORIA_SERVICIO,
        PV_USR_INGRESO,
        NOW()
    );

END IF;
COMMIT;
END$$
DELIMITER ;

-- =============================================================================
-- MODULO PERSONAS - PROCEDIMIENTO ALMACENADO UPDATE Y SOFT DELETE
-- FILTRADO POR MEDIO DE IFS ANIDADOS
-- =============================================================================

DELIMITER $$
CREATE PROCEDURE UPD_PERSONAS (
 IN PV_ACCION            VARCHAR(20),    
 IN PI_COD_PERSONA       BIGINT,
 IN PV_DNI               VARCHAR(255),
 IN PV_PRIMER_NOMBRE     VARCHAR(255),
 IN PV_SEGUNDO_NOMBRE    VARCHAR(255),
 IN PV_APELLIDO          VARCHAR(255),
 IN PC_SEXO              ENUM('M','F','O','D'),
 IN PC_EST_CIVIL         ENUM('S','C','V'),
 IN PI_EDAD              TINYINT,
 IN PI_NUM_AREA_CEL      SMALLINT,
 IN PI_NUM_TELEFONO_CEL  INT,
 IN PI_NUM_AREA_OFI      SMALLINT,
 IN PI_NUM_TELEFONO_OFI  INT,
 IN PV_USUARIO_CORREO    VARCHAR(200),
 IN PV_SERVIDOR_CORREO   VARCHAR(200),
 IN PV_NOMBRE_USR        VARCHAR(255),
 IN PV_CLAVE             VARCHAR(2000),
 IN PV_TOKEN             VARCHAR(6),
 IN PC_IND_USR           ENUM('1','0'),
 IN PC_IND_PRIMER_ING    ENUM('1','0'),
 IN PV_NOM_EMPRESA_CLI   VARCHAR(255),
 IN PC_IND_CLIENTE       ENUM('1','0'),
 IN PV_CARGO             VARCHAR(100),
 IN PD_FEC_CONTRATACION  DATE,
 IN PN_SALARIO           DECIMAL(10,2),
 IN PV_EMPRESA_PROV      VARCHAR(150),
 IN PV_CATEGORIA_SERV    VARCHAR(100),
 IN PV_USR_INGRESO       VARCHAR(255))
BEGIN
START TRANSACTION;

/* =============================================================================
   UPDATE
   ============================================================================= */
IF PV_ACCION = 'UPDATE' THEN

    
    IF PV_SEGUNDO_NOMBRE IS NULL THEN
      UPDATE PA_PERSONAS
      SET DNI            = IFNULL(PV_DNI, DNI),
          PRIMER_NOMBRE  = IFNULL(PV_PRIMER_NOMBRE, PRIMER_NOMBRE),
          APELLIDO       = IFNULL(PV_APELLIDO, APELLIDO),
          SEXO           = IFNULL(PC_SEXO, SEXO),
          EST_CIVIL      = IFNULL(PC_EST_CIVIL, EST_CIVIL),
          EDAD           = IFNULL(PI_EDAD, EDAD),
          USR_INGRESO    = PV_USR_INGRESO,
          FEC_INGRESO    = NOW()
      WHERE COD_PERSONA  = PI_COD_PERSONA;
    ELSE
      UPDATE PA_PERSONAS
      SET DNI            = IFNULL(PV_DNI, DNI),
          PRIMER_NOMBRE  = IFNULL(PV_PRIMER_NOMBRE, PRIMER_NOMBRE),
          SEGUNDO_NOMBRE = PV_SEGUNDO_NOMBRE,
          APELLIDO       = IFNULL(PV_APELLIDO, APELLIDO),
          SEXO           = IFNULL(PC_SEXO, SEXO),
          EST_CIVIL      = IFNULL(PC_EST_CIVIL, EST_CIVIL),
          EDAD           = IFNULL(PI_EDAD, EDAD),
          USR_INGRESO    = PV_USR_INGRESO,
          FEC_INGRESO    = NOW()
      WHERE COD_PERSONA  = PI_COD_PERSONA;
    END IF;

    
    SELECT @COD_TELCEL :=  t.COD_TELEFONO
                           from REL_PERSONAS_TELEFONOS r, PA_TELEFONOS t
                           where r.COD_TELEFONO = t.COD_TELEFONO
                           and r.COD_PERSONA = PI_COD_PERSONA
                           and t.TIP_TELEFONO = 'C';

    IF PI_NUM_AREA_CEL IS NOT NULL AND PI_NUM_TELEFONO_CEL IS NOT NULL THEN
      UPDATE PA_TELEFONOS
      SET NUM_AREA     = PI_NUM_AREA_CEL,
          NUM_TELEFONO = PI_NUM_TELEFONO_CEL,
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_TELEFONO = @COD_TELCEL;
    END IF;

    
    SELECT @COD_TELOFI :=  t.COD_TELEFONO
                           from REL_PERSONAS_TELEFONOS r, PA_TELEFONOS t
                           where r.COD_TELEFONO = t.COD_TELEFONO
                           and r.COD_PERSONA = PI_COD_PERSONA
                           and t.TIP_TELEFONO = 'O';

    IF PI_NUM_AREA_OFI IS NOT NULL AND PI_NUM_TELEFONO_OFI IS NOT NULL THEN
      UPDATE PA_TELEFONOS
      SET NUM_AREA     = PI_NUM_AREA_OFI,
          NUM_TELEFONO = PI_NUM_TELEFONO_OFI,
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_TELEFONO = @COD_TELOFI;
    END IF;

    
    SELECT @COD_CORREO :=  c.COD_CORREO
                           from REL_PERSONAS_CORREOS r, PA_CORREOS c
                           where r.COD_CORREO = c.COD_CORREO
                           and r.COD_PERSONA = PI_COD_PERSONA;

    IF PV_USUARIO_CORREO IS NOT NULL AND PV_SERVIDOR_CORREO IS NOT NULL THEN
      UPDATE PA_CORREOS
      SET USUARIO_CORREO  = PV_USUARIO_CORREO,
          SERVIDOR_CORREO = PV_SERVIDOR_CORREO,
          USR_INGRESO     = PV_USR_INGRESO,
          FEC_INGRESO     = NOW()
      WHERE COD_CORREO    = @COD_CORREO;
    END IF;

    
    SELECT @COD_USUARIO :=  u.COD_USUARIO
                            from USUARIOS u
                            where u.COD_PERSONA = PI_COD_PERSONA;

    IF PV_NOMBRE_USR IS NOT NULL THEN
      IF PV_CLAVE IS NOT NULL THEN
        UPDATE USUARIOS
        SET NOMBRE         = PV_NOMBRE_USR,
            CLAVE          = PV_CLAVE,
            TOKEN          = IFNULL(PV_TOKEN, TOKEN),
            IND_USR        = IFNULL(PC_IND_USR, IND_USR),
            IND_PRIMER_ING = IFNULL(PC_IND_PRIMER_ING, IND_PRIMER_ING),
            USR_INGRESO    = PV_USR_INGRESO,
            FEC_INGRESO    = NOW()
        WHERE COD_USUARIO  = @COD_USUARIO;
      ELSE
        UPDATE USUARIOS
        SET NOMBRE         = PV_NOMBRE_USR,
            TOKEN          = IFNULL(PV_TOKEN, TOKEN),
            IND_USR        = IFNULL(PC_IND_USR, IND_USR),
            IND_PRIMER_ING = IFNULL(PC_IND_PRIMER_ING, IND_PRIMER_ING),
            USR_INGRESO    = PV_USR_INGRESO,
            FEC_INGRESO    = NOW()
        WHERE COD_USUARIO  = @COD_USUARIO;
      END IF;
    END IF;


    SELECT @COD_CLIENTE :=  cl.COD_CLIENTE
                            from PA_CLIENTES cl
                            where cl.COD_PERSONA = PI_COD_PERSONA;

    IF PV_NOM_EMPRESA_CLI IS NOT NULL THEN
      UPDATE PA_CLIENTES
      SET NOM_EMPRESA  = PV_NOM_EMPRESA_CLI,
          IND_CLIENTE  = IFNULL(PC_IND_CLIENTE, IND_CLIENTE),
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_CLIENTE = @COD_CLIENTE;
    ELSEIF PC_IND_CLIENTE IS NOT NULL THEN
      UPDATE PA_CLIENTES
      SET IND_CLIENTE  = PC_IND_CLIENTE,
          USR_INGRESO  = PV_USR_INGRESO,
          FEC_INGRESO  = NOW()
      WHERE COD_CLIENTE = @COD_CLIENTE;
    END IF;

    
    SELECT @COD_EMPLEADO :=  e.COD_EMPLEADO
                             from PA_EMPLEADOS e
                             where e.COD_PERSONA = PI_COD_PERSONA;

    IF PV_CARGO IS NOT NULL THEN
      UPDATE PA_EMPLEADOS
      SET CARGO            = PV_CARGO,
          FEC_CONTRATACION = IFNULL(PD_FEC_CONTRATACION, FEC_CONTRATACION),
          SALARIO          = IFNULL(PN_SALARIO, SALARIO),
          USR_INGRESO      = PV_USR_INGRESO,
          FEC_INGRESO      = NOW()
      WHERE COD_EMPLEADO   = @COD_EMPLEADO;
    ELSEIF PN_SALARIO IS NOT NULL THEN
      UPDATE PA_EMPLEADOS
      SET SALARIO          = PN_SALARIO,
          FEC_CONTRATACION = IFNULL(PD_FEC_CONTRATACION, FEC_CONTRATACION),
          USR_INGRESO      = PV_USR_INGRESO,
          FEC_INGRESO      = NOW()
      WHERE COD_EMPLEADO   = @COD_EMPLEADO;
    END IF;

    
    SELECT @COD_PROVEEDOR :=  p.COD_PROVEEDOR
                              from PA_PROVEEDORES p
                              where p.COD_PERSONA = PI_COD_PERSONA;

    IF PV_EMPRESA_PROV IS NOT NULL THEN
      UPDATE PA_PROVEEDORES
      SET EMPRESA            = PV_EMPRESA_PROV,
          CATEGORIA_SERVICIO = IFNULL(PV_CATEGORIA_SERV, CATEGORIA_SERVICIO),
          USR_INGRESO        = PV_USR_INGRESO,
          FEC_INGRESO        = NOW()
      WHERE COD_PROVEEDOR    = @COD_PROVEEDOR;
    END IF;

/* =============================================================================
   SOFT DELETE
   ============================================================================= */
ELSEIF PV_ACCION = 'SOFT_DELETE' THEN

    
    UPDATE USUARIOS
    SET IND_USR     = '0',
        USR_INGRESO = PV_USR_INGRESO,
        FEC_INGRESO = NOW()
    WHERE COD_PERSONA = PI_COD_PERSONA;
    

END IF;

COMMIT;
END$$
DELIMITER ;

-- =============================================================================
-- PROCEDIMIENTO DE SELECT MODULO DE PERSONAS
-- FILTRADO POR IFS ANIDADOS
-- =============================================================================

DELIMITER $$
CREATE PROCEDURE SP_PA_SELECT(
    IN  pv_accion          VARCHAR(255)
   ,IN  pi_cod_persona     BIGINT
   ,IN  pi_cod_telefono    BIGINT
   ,IN  pi_cod_rel_pertel  BIGINT
   ,IN  pi_cod_correo      BIGINT
   ,IN  pi_cod_rel_percor  BIGINT
   ,IN  pi_cod_tipo_usr    BIGINT
   ,IN  pi_cod_usuario     BIGINT
   ,IN  pi_cod_tipo_cli    BIGINT
   ,IN  pi_cod_cliente     BIGINT
   ,IN  pi_cod_empleado    BIGINT
   ,IN  pi_cod_proveedor   BIGINT
)
BEGIN

    START TRANSACTION;

    IF pv_accion = 'SEL_PA_PERSONAS' THEN

        SELECT
             COD_PERSONA
            ,DNI
            ,PRIMER_NOMBRE
            ,SEGUNDO_NOMBRE
            ,APELLIDO
            ,SEXO
            ,EST_CIVIL
            ,EDAD
            ,TIP_PERSONA
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_PERSONAS
        WHERE
            (pi_cod_persona IS NULL OR COD_PERSONA = pi_cod_persona);

    ELSEIF pv_accion = 'SEL_PA_TELEFONOS' THEN

        SELECT
             COD_TELEFONO
            ,NUM_AREA
            ,NUM_TELEFONO
            ,TIP_TELEFONO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_TELEFONOS
        WHERE
            (pi_cod_telefono IS NULL OR COD_TELEFONO = pi_cod_telefono);

    ELSEIF pv_accion = 'SEL_REL_PERSONAS_TELEFONOS' THEN

        SELECT
             COD_REL_PERTEL
            ,COD_PERSONA
            ,COD_TELEFONO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            REL_PERSONAS_TELEFONOS
        WHERE
            (pi_cod_rel_pertel IS NULL OR COD_REL_PERTEL = pi_cod_rel_pertel)
        AND (pi_cod_persona    IS NULL OR COD_PERSONA    = pi_cod_persona)
        AND (pi_cod_telefono   IS NULL OR COD_TELEFONO   = pi_cod_telefono);

    ELSEIF pv_accion = 'SEL_PA_CORREOS' THEN

        SELECT
             COD_CORREO
            ,USUARIO_CORREO
            ,SERVIDOR_CORREO
            ,TIP_CORREO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_CORREOS
        WHERE
            (pi_cod_correo IS NULL OR COD_CORREO = pi_cod_correo);

    ELSEIF pv_accion = 'SEL_REL_PERSONAS_CORREOS' THEN

        SELECT
             COD_REL_PERCOR
            ,COD_PERSONA
            ,COD_CORREO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            REL_PERSONAS_CORREOS
        WHERE
            (pi_cod_rel_percor IS NULL OR COD_REL_PERCOR = pi_cod_rel_percor)
        AND (pi_cod_persona    IS NULL OR COD_PERSONA    = pi_cod_persona)
        AND (pi_cod_correo     IS NULL OR COD_CORREO     = pi_cod_correo);

    ELSEIF pv_accion = 'SEL_PA_TIPO_USUARIOS' THEN

        SELECT
             COD_TIPO_USR
            ,NOM_TIPO
            ,DES_TIPO
        FROM
            PA_TIPO_USUARIOS
        WHERE
            (pi_cod_tipo_usr IS NULL OR COD_TIPO_USR = pi_cod_tipo_usr);

    ELSEIF pv_accion = 'SEL_USUARIOS' THEN

        SELECT
             COD_USUARIO
            ,COD_PERSONA
            ,COD_TIPO_USR
            ,NOMBRE
            ,TOKEN
            ,IND_USR
            ,IND_PRIMER_ING
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            USUARIOS
        WHERE
            (pi_cod_usuario IS NULL OR COD_USUARIO = pi_cod_usuario)
        AND (pi_cod_persona IS NULL OR COD_PERSONA = pi_cod_persona);

    ELSEIF pv_accion = 'SEL_PA_TIPO_CLIENTES' THEN

        SELECT
             COD_TIPO_CLI
            ,NOM_TIPO_CLI
            ,DES_TIPO_CLI
            ,IND_TIPO_CLI
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_TIPO_CLIENTES
        WHERE
            (pi_cod_tipo_cli IS NULL OR COD_TIPO_CLI = pi_cod_tipo_cli);

    ELSEIF pv_accion = 'SEL_PA_CLIENTES' THEN

        SELECT
             COD_CLIENTE
            ,COD_PERSONA
            ,COD_TIPO_CLI
            ,NOM_EMPRESA
            ,IND_CLIENTE
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_CLIENTES
        WHERE
            (pi_cod_cliente IS NULL OR COD_CLIENTE = pi_cod_cliente)
        AND (pi_cod_persona IS NULL OR COD_PERSONA = pi_cod_persona);

    ELSEIF pv_accion = 'SEL_PA_EMPLEADOS' THEN

        SELECT
             COD_EMPLEADO
            ,COD_PERSONA
            ,CARGO
            ,FEC_CONTRATACION
            ,SALARIO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_EMPLEADOS
        WHERE
            (pi_cod_empleado IS NULL OR COD_EMPLEADO = pi_cod_empleado)
        AND (pi_cod_persona  IS NULL OR COD_PERSONA  = pi_cod_persona);

    ELSEIF pv_accion = 'SEL_PA_PROVEEDORES' THEN

        SELECT
             COD_PROVEEDOR
            ,COD_PERSONA
            ,EMPRESA
            ,CATEGORIA_SERVICIO
            ,USR_INGRESO
            ,FEC_INGRESO
        FROM
            PA_PROVEEDORES
        WHERE
            (pi_cod_proveedor IS NULL OR COD_PROVEEDOR = pi_cod_proveedor)
        AND (pi_cod_persona   IS NULL OR COD_PERSONA   = pi_cod_persona);

    END IF;

    COMMIT;

END$$
DELIMITER ;
